# Access the Google API

First we need to make an account and login [here](https://console.cloud.google.com/apis).
First one need to create a new project. In the new project click the credentials tab, where one can add an API-key by clicking the "+ CREATE CREDENTIALS" button and selecting the "API-key" option.
Here you can add restrictions like only letting your IP use this key. Copy the key for later use.
Before the key can be used it needs to be enabled.
By executing a request the server response will contain a url where the key can be enabled:
https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=[your project id]

In [1]:
import requests

One can use the youtube-v3 api url, but the  second one provides additional features, namely getting the music part of the description of a video that is a mix of multiple videos

In [2]:
URL='https://youtube.googleapis.com/youtube/v3/'
API_KEY='AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI'

The URL for our API-requests contains a key to define the requested items and an id or search string that we must add to the request.

In [3]:
from enum import Enum

class Items(Enum):
    CHANNELS=('channels','id')
    PLAYLISTS=('playlists','channelId')
    PLAYLIST_ITEMS=('playlistItems','playlistId')
    VIDEOS=('videos','id')
    SEARCH=('search','q')
    SEARCH_VIDEO=('search','videoId')

The part defines which content is accessed. This depends on the requested items.
The most important are:

In [4]:
class Part(Enum):
    ID='id'
    SNIPPET='snippet'
    CONTENTDETAILS='contentDetails'
    STATUS='status'
    STATISTICS='statistics'
    FILEDETAILS='fileDetails'

The YoutubeApi class handles all requests, as long as the parts and items are defined.

In [5]:
from youtube.yt_api import *

Lets test it with a request to get the playlists from a channel. You can get the id with a browser by opening a video published by the channel and use the video id

In [ ]:
myChannel = 'UC-hQLecyL6lx1lCCy3tTQyg'

videoId = 'y9k55TGBZXk'
request = YoutubeApi(API_KEY,URL)
(video,meta) = request.get(videoId,Items.VIDEOS,[Part.CONTENTDETAILS,Part.SNIPPET])
channelId = video[0]['snippet']['channelId']
print(channelId)

https://youtube.googleapis.com/youtube/v3/videos?part=contentDetails,snippet&id=y9k55TGBZXk&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI

In [9]:
# get the first playlist
playlists = request.get(channelId,Items.PLAYLISTS,[Part.CONTENTDETAILS,Part.SNIPPET],maxResults=50)
playlistId = playlists[0]['id']

https://youtube.googleapis.com/youtube/v3/playlists?part=contentDetails,snippet&channelId=UC1J5I46pnK6ZsyMADVr0zYw&maxResults=50&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI

TypeError: list indices must be integers or slices, not str

In [ ]:
#get the first video id
videos = request.get(playlistId,request_type=Items.PLAYLIST_ITEMS,parts=[Part.SNIPPET])
videoId = videos[0]['snippet']['resourceId']['videoId']
videos[0]

https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoWzS0i1TbZyPihQpNuolJoJ&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI

{'kind': 'youtube#playlistItem',
 'etag': 'e13RbKeB5P8eVrxWkEt_Dq4dInU',
 'id': 'UExqUDhldmRya2FvV3pTMGkxVGJaeVBpaFFwTnVvbEpvSi4wMTcyMDhGQUE4NTIzM0Y5',
 'snippet': {'publishedAt': '2023-02-06T07:08:34Z',
  'channelId': 'UC1J5I46pnK6ZsyMADVr0zYw',
  'title': 'Peyotes - What Causes Psychosis',
  'description': 'Subscribe: http://bit.ly/SubscribeSangoma\nBuy: https://sangomarecs.bandcamp.com/album/hikuri\nSangoma Records presents the new EP by Peyotes from Athens, Greece.\nWith his second EP after “Wierdayz” from 2018, Panos creates new sonic realms to explore the inner labyrinth.  Once again Rosenfeldtown provided us with another masterpiece from his psychonaut art series , perfectly fitting to the this release accompanied by the mastering of Nektarios (Ballistic Mastering). Enough written – let the plant do the talking.\nSangoma Records - Medicinal music\n\n~~~~~~~~~~~~~~~~~\n:: Mastering: Ballistic Mastering\n:: Art: Rosenfeldtown\n:: Animation: Maurizio Girioli @ Girimmo\n~~~~~~~~~~~~~~~~~\n\nPeyotes - Hikury, Released 2023-02-06, Sangoma Records\n\nCheck Out:\nX (compiled by Emiel & Daksinamurti)\nhttps://www.youtube.com/watch?v=TT9KAyiclbw&list=PLjP8evdrkaoWRNRPhaNNPx09p5bb__FBq&index=1\n\n#trance\u200b #psytrance\u200b #foresttrance\u200b #foresttrance #Peyotes\n\nFollow us:\n\nFacebook: https://www.facebook.com/sangomarecords/\nWebsite: http://sangomarecords.com/\nSoundcloud: https://soundcloud.com/sangoma-recs\nInstagram: https://www.instagram.com/sangoma.records/\n\nSangoma Records, founded in 2011 out of enthusiasm for psychedelic culture and music by the virtuoso Emiel / Gata Freak and cultural anthropologist Daksinamurti – both DJs for over a decade.\n\nThe aim of Sangoma Records is to release psychedelic trance without any stubborn stylistic definitions and boundaries. Their darkpsy, shamanic forest trance is made by unique new talents and established artists who don’t follow trends and instead deliver something new and outside of boxes. The aim of “Sangoma” is not only to release authentic psytrance but also to observe, support and create culture. Organic medicine for your ears.\n\nThis channel is powered by Trancentral.\n\nThis channel is powered by Trancentral\nSubscribe for updates: http://bit.ly/TrancentralSubscribe',
  'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/y9k55TGBZXk/default.jpg',
    'width': 120,
    'height': 90},
   'medium': {'url': 'https://i.ytimg.com/vi/y9k55TGBZXk/mqdefault.jpg',
    'width': 320,
    'height': 180},
   'high': {'url': 'https://i.ytimg.com/vi/y9k55TGBZXk/hqdefault.jpg',
    'width': 480,
    'height': 360},
   'standard': {'url': 'https://i.ytimg.com/vi/y9k55TGBZXk/sddefault.jpg',
    'width': 640,
    'height': 480},
   'maxres': {'url': 'https://i.ytimg.com/vi/y9k55TGBZXk/maxresdefault.jpg',
    'width': 1280,
    'height': 720}},
  'channelTitle': 'Sangoma Records',
  'playlistId': 'PLjP8evdrkaoWzS0i1TbZyPihQpNuolJoJ',
  'position': 0,
  'resourceId': {'kind': 'youtube#video', 'videoId': 'y9k55TGBZXk'},
  'videoOwnerChannelTitle': 'Sangoma Records',
  'videoOwnerChannelId': 'UC1J5I46pnK6ZsyMADVr0zYw'}}

In [ ]:
item = request.get(videoId,request_type=Items.VIDEOS,parts=[Part.ID,Part.SNIPPET,Part.CONTENTDETAILS,Part.STATISTICS])

https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=y9k55TGBZXk&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI

In [ ]:
def getVideoData(videoId):
    items = request.get(videoId,request_type=Items.VIDEOS,parts=[Part.ID,Part.SNIPPET,Part.CONTENTDETAILS,Part.STATISTICS])
    res = []
    for  item in items:
        data = []
        data.append(item['id'])
        data.append(item['etag'])

        snippet = item['snippet']
        data.append(snippet['title'])
        data.append(snippet['channelId'])
        data.append(snippet['channelTitle'])
        data.append(snippet['publishedAt'])
        data.append(snippet['description'])
        data.append(snippet['categoryId'])
        if 'tags' in snippet.keys():
            data.append(snippet['tags'])
        else:
            data.append([])

        contentDetails = item['contentDetails']
        data.append(contentDetails['duration'])
        data.append(contentDetails['dimension'])
        data.append(contentDetails['definition'])
        statistics = item['statistics']
        data.append(statistics['viewCount'])
        data.append(statistics['likeCount'])
        if 'dislikeCount' in snippet.keys():
            data.append(statistics['dislikeCount'])
        else:
            data.append([])
        data.append(statistics['favoriteCount'])
        data.append(statistics['commentCount'])
        res.append(data)
    return res

In [ ]:
import pandas as pd
columns = ['id','etag','title','channelId','channelTitle','publishedAt','description','categoryId','tags'
           ,'duration','dimension','definition','viewCount','likeCount','dislikeCount','favoriteCount','commentCount']
df = pd.DataFrame(columns=columns)

now lets get all of that channels videos

In [ ]:
for playlist in playlists:
    #get the first video id
    playlistItem = request.get(playlist['id'],request_type=Items.PLAYLIST_ITEMS,parts=[Part.SNIPPET])
    if playlist is not None and len(playlistItem)>0:
        ids = playlistItem[0]['snippet']['resourceId']['videoId']
        for item in playlistItem:
            ids += "%2C"+item['snippet']['resourceId']['videoId']
        
        for item in getVideoData(ids):
            df.loc[len(df)] = item

https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoWzS0i1TbZyPihQpNuolJoJ&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=y9k55TGBZXk%2Cy9k55TGBZXk%2CgdjxJ33nRiY%2C30wid71tq8c&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoVpZJGuG23jgAjTX8PjtpOq&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=NgM7wZLCVCM%2CNgM7wZLCVCM%2CPal1KNAfxnE%2CbLWPGuPtPGY&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoWRNRPhaNNPx09p5bb__FBq&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=TT9KAyiclbw%2CTT9KAyiclbw%2C4Uv1GfBg-5E%2C_RkNnjDCcZM%2CQIvOf2FFWPI%2Cmi_Uy1pu9Jo%2CNcJ2BStZCFI%2CXk0TCopJKIw%2Cwl7qMjgVlwM%2CA4fTHq-01ZI%2CLHXfhbpQQW0&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoW0RXKS0cVAmdnm8ZvOg7pP&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=oIdO7FLesVQ%2CoIdO7FLesVQ%2CBRvkf_ynhTQ%2CcoPvbPcFS3I%2ChAALIaVPVHc&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoV8LXAazrdlYnOOcotv7geZ&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=5dyrpF5MmR8%2C5dyrpF5MmR8%2Ci6Yw2Ut1EsY%2Ci5s-e4YH2ek&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoV6KLm5E0MLrXPZcQ-khQ0M&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=cLPrmQraS4Q%2CcLPrmQraS4Q%2C9Si_bmp8rcg%2CFOIFxj5TdLI%2CEoEZx7GHvWs%2CLX3xbtZP2PA%2CohoKZ5X84jc%2CvGzOhv36dIQ%2Cv3QKLN-7NhU%2CVW_zn00_mf4%2COD2sTOpy-UQ&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoW6FUtDk69_kSmi_zD7ceHm&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=37Qg0fgYNlk%2C37Qg0fgYNlk%2CGgFm680E8S8%2CoZ_e5dQyRUc%2Cvak7W-3L5EY&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoWpj8FEkpHsUk7uw4f9b0Pc&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=BHGM6yKTh5c%2CBHGM6yKTh5c%2CISEWzoMgJzM%2CPQXsWq9i6JI%2CQHE6q5L-p3Y%2CS0NgLWzgyks%2CWMXleNZpWLY%2C__aj4KwKMjw%2CcCa02gX9A5s%2CekLWy5IOVsc%2Cl0-7Sq5Vf2U&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoWLZEvWf8V9ySNLgNOUkaU-&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=GJXjRzQoWbY%2CGJXjRzQoWbY%2Cul4VIfuAQnA%2C4mx2GolA-kg%2Ce7zhCM16xJ4%2CdlOxVYqRYJ0%2C4tummy-s1xg%2CKHY7WDzQ4BI%2CA4bRJk_n3mI%2CMt_zTMT5EuQ%2CDre2s1Z96VA&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoVZlxmVnfJIU4YRUfE4vfCP&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=1zebL2qZZXg%2C1zebL2qZZXg%2Cy_EhnA01w7g%2CjDPpXOSqamA%2C0r-jkM8X4Fk&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoXu1icw_Qr8AvkkaoHh0LCS&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=4Q9NZDZY6nQ%2C4Q9NZDZY6nQ%2C-_lNUytc_rY%2CqfMYtxDF1m8&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoVz54CIttA0w5QOcE-VvWcm&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=QIupVNQqx8w%2CQIupVNQqx8w%2CxAHHcQnn480%2CzUmdSJKh0UY%2C4UFKluOwnwY%2CRAQxjPZcZ-U%2CCARiWzehHdc%2C7AGobL2HYus%2C9Qf27zed-Us%2C0DYQXM99jdU%2C72lW7zddHtQ&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoUC7ez_KrEs5Q3SWG0BgWZc&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=d9iq1e-pcG8%2Cd9iq1e-pcG8%2CyRR0y6rffVY%2Cczr6j6FXuw4%2CTOlQK5LUk-Y&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoUivbcs3g410ca3NorP0oct&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=aHnAbIlA_f0%2CaHnAbIlA_f0%2CNP8yJjkNtnA%2C0BTKzJfkulQ%2CGtXmb0SE_OE%2CjEf1WPgSgCM&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoUMaEX3T2BrRjeEWatdtzop&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=ATuyvwMV4no%2CATuyvwMV4no%2CMuKt4ZOE22s%2CEajiokg2mkQ%2Cv3ZYfead5n4%2CDcn81jBUiy8%2CiHDnRQjXfOI%2CdF59_UEq5ZM%2CL5aFb6IqyHc%2CztaNeXC3cqc%2CsW_0ebZV5T8&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoU9g69kIDeVe5mIjrkW3low&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=2_70bSWbd9w%2C2_70bSWbd9w%2CNGO0A3jlWD8%2Cn6bO405oDaQ%2C9YtjIbRAp3I%2Cy6DgTgBj-1E&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoUc8jk_6T0qLpxs7VZ0gzhC&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=DefUSyLQ8dI%2CDefUSyLQ8dI%2CEI4JBV-FUdY%2CgIlaOorgeHM&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoUDE-uAH68z6L1slkgYMHix&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=UIXQsl7kETo%2CUIXQsl7kETo%2CcXv6bqPaIkY%2C-FKAAOGGMAQ%2Cy9I61a1bYyE%2CuoWEavMLvGE%2C7wgmZ_pBGl4%2CnlKmOh2gZRI%2CvncuC8SO33Q%2CPRC3TrTFRDc%2CSc_3RHmBvFk&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoWAQEIgW8NYnqXLoSG3KjPS&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=qn8Bm4B8VZk%2Cqn8Bm4B8VZk%2Ccluah6zPN_Y%2CFNTnNYeFLFA%2CQr5OU3tYzcQ&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoWZZcTIJyjWZKX80QeDsd46&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=xNl8JktK-ZI%2CxNl8JktK-ZI%2ChCBaTGTkWa4%2ChgMmcyPuxpw%2Ctdayel6Qq_s%2CAVMLrwu0rtI%2CaNzx6rW_Jrw%2CWUijJlHnpHY%2CBVNVVfF3t0A%2CdHBYnFXgX7k%2C3lkvSW8dPK4&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoXa3-vqZ1JW88h95A5-_8x2&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=WN1cLnWXwoQ%2CWN1cLnWXwoQ%2C24_YV1J-Wmw%2CH3FSe3T1s88%2C8tI5LoFXrnA%2CyzzYklZ-cW8%2CBc7RloQ_IFc%2CncECgqr9iyk&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoWfotHhWSXL_1G-S48sIACL&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=6X8xXBSroFQ%2C6X8xXBSroFQ%2Cw4hX1kfH8zI%2CvHjFFQM7bLY%2CB43KW1IUSME&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoXkfe7aC81zCWDs63cAAp1s&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=QPy5daXBtLA%2CQPy5daXBtLA%2C9E1eKgLotUw%2CmJ3i9CHbyNc%2CLdmqM-nyKgU&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoVx-uT-OST6ayxgacORHbp2&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=JyxALAe_M-0%2CJyxALAe_M-0%2C6jvntooGoD4%2CU-ztZ1CAikY%2CBrwj2tW2bXI%2ClQGI6_FSNx0%2C_XCrfQcj4Do%2CZeAaJwy3pbg%2CLONdcroccw4%2CYvebwJH5MMU&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoWi0Zh3A5y8EjS8MvTSvruZ&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=2Fr9BwKoZts%2C2Fr9BwKoZts%2CEVdx5UnoqRw%2CM1A7vduaq28%2CYWDiA_gEC24&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoXDWlzifKWBElNEo5NOKUw1&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=sRFEZMy2uU0%2CsRFEZMy2uU0%2CThJZLML77Pc%2CNmSZZ0p_kzk&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoU8vmH3ZR7orYt4YT7C-VFB&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=2lGMEV0jB_M%2C2lGMEV0jB_M%2Coxp5c3ipdn8%2C2ejDQ1dspEE%2CzAca-ahjAD8%2CUjK-xbmOfMM%2CzUXPW5QH6EE%2C7uQWdFyVufc%2CPByIhnDVahE%2CyBNQKX5brac%2CRe6LCpN-ilA&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoVuZcW04LFtodzGwCHxpMcQ&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=qgqAU-FEthE%2CqgqAU-FEthE%2CVnmsNos3f3o%2CxkSK3LHSCRE%2CdzP2XK4pZh4&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoUe5ywMl4FSX3jlDjHf1AkC&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=VKlf8uE81gI%2CVKlf8uE81gI%2CBbECXUiQrP0%2CLezXL1-GXqU%2C7N8bIg8F8BY%2C3i7rrZmVEdI%2CUsXsunf_2zA%2CiEQxu8vp3nU%2Cwn8fSwrhu70%2CbPT88WoCSZA%2CR-Gt_vK1Luc&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoXFMWkEa-Al7ojUzyqtMcuD&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=RhEJiXry_BM%2CRhEJiXry_BM%2CA-EaS3iqGV8%2CBTfSZ4psVkc%2C-JALCHRvgKY%2C4f8-rxrBW6w%2CysnZ4Hb0gKg%2CJdAFyhm8_eM%2CrWa18m1_OCY%2CqWmuXtb8zvw%2CNIlQd1_z-h4&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoX1Ey0Y2KeT7JfcCvk_htrq&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=LoRqoqFuBZE%2CLoRqoqFuBZE%2Cl3foUjb4Q0o%2CXFanhczCxJY%2COidXjB8ePjU%2CWG2RKMUZ-Uo%2CmxpS6jgFn5o%2CGZ8b6XrsEv8%2CANcPhOR2zuI%2CW2DU7O0S4x8%2Ce5KIb2gsZ2o&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoXZYUqw9XaRYQBl-lxEWw2H&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=PXFkSa9rFtQ%2CPXFkSa9rFtQ%2C_7ag02PAa30&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoU_3eJpKsyXD_eE5LPQifb4&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/videos?part=id&part=snippet&part=contentDetails&part=statistics&id=FJ9lHJlroRA%2CFJ9lHJlroRA%2CGCZ1sXt6WlI%2CyNaHr7ZlSj8&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI
https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=PLjP8evdrkaoWvUqOOSDBwx2rxjTulPD5V&maxResults=10&key=AIzaSyDm9NUppwHLXdZ6uWmdd4Swzg0kyI78TAI

KeyboardInterrupt:

In [ ]:
df

,id,etag,title,channelId,channelTitle,publishedAt,description,categoryId,tags,duration,dimension,definition,viewCount,likeCount,dislikeCount,favoriteCount,commentCount
0,y9k55TGBZXk,L51Uj1dkkM_Stjt04MhTLEeZJxU,Peyotes - What Causes Psychosis,UC1J5I46pnK6ZsyMADVr0zYw,Sangoma Records,2023-02-06T07:08:39Z,Subscribe: http://bit.ly/SubscribeSangoma\nBuy...,10,"[sangoma, psytrance, psychedelic trance, darkp...",PT7M23S,2d,hd,423,41,[],0,8
1,y9k55TGBZXk,L51Uj1dkkM_Stjt04MhTLEeZJxU,Peyotes - What Causes Psychosis,UC1J5I46pnK6ZsyMADVr0zYw,Sangoma Records,2023-02-06T07:08:39Z,Subscribe: http://bit.ly/SubscribeSangoma\nBuy...,10,"[sangoma, psytrance, psychedelic trance, darkp...",PT7M23S,2d,hd,423,41,[],0,8
2,gdjxJ33nRiY,3_66wc0PPl2NOT4DfIgM8HZ8I70,Peyotes ft. Twisted Perception - Less is More,UC1J5I46pnK6ZsyMADVr0zYw,Sangoma Records,2023-02-06T07:08:41Z,Subscribe: http://bit.ly/SubscribeSangoma\nBuy...,10,"[sangoma, psytrance, psychedelic trance, darkp...",PT6M40S,2d,hd,364,37,[],0,2
3,30wid71tq8c,zSdmS4QLbKq2TFYJvUP_U-iu0ww,Peyotes - Hikury,UC1J5I46pnK6ZsyMADVr0zYw,Sangoma Records,2023-02-06T07:08:44Z,Subscribe: http://bit.ly/SubscribeSangoma\r\nB...,10,"[sangoma, psytrance, psychedelic trance, darkp...",PT7M36S,2d,hd,1258,134,[],0,15
4,NgM7wZLCVCM,CIVEx_J4ySNBxjd3AYB0z1yyoxk,San and Tac - Chasing Urmahlullu,UC1J5I46pnK6ZsyMADVr0zYw,Sangoma Records,2023-01-30T10:46:48Z,Subscribe: http://bit.ly/SubscribeSangoma\nBuy...,10,"[sangoma, psytrance, psychedelic trance, darkp...",PT6M30S,2d,hd,1037,81,[],0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,960fMzFBh7Q,uQLslXNO4b9EIruBBC4jjd9hLOs,Kaos - A Real Good Time,UC1J5I46pnK6ZsyMADVr0zYw,Sangoma Records,2019-12-06T07:44:57Z,Subscribe: http://bit.ly/SubscribeSangoma\nVA ...,10,"[sangoma, psytrance, psychedelic trance, darkp...",PT6M51S,2d,hd,2140,83,[],0,2
359,fFYB06N_nlQ,xp9YCuTzyT3N3QZmE-gXkf68DQc,Nargun & The Verge - Birds of Paradise,UC1J5I46pnK6ZsyMADVr0zYw,Sangoma Records,2019-12-06T07:44:56Z,Subscribe: http://bit.ly/SubscribeSangoma\nVA ...,10,"[sangoma, psytrance, psychedelic trance, darkp...",PT7M31S,2d,hd,1738,66,[],0,1
360,MqA6zaHM7PE,kNLDENCUheYSdIvIDTj0EHmq3jU,Archaic - Animystic,UC1J5I46pnK6ZsyMADVr0zYw,Sangoma Records,2019-12-06T07:44:56Z,Subscribe: http://bit.ly/SubscribeSangoma\nVA ...,10,"[sangoma, psytrance, psychedelic trance, darkp...",PT9M16S,2d,hd,1962,75,[],0,2
361,hTVH_R6X2-8,Mnz7pSND0M-Y_wf-WEIk40Vqxo8,Tengri - Yantra On The Nightsky,UC1J5I46pnK6ZsyMADVr0zYw,Sangoma Records,2019-12-06T07:44:56Z,Subscribe: http://bit.ly/SubscribeSangoma\nVA ...,10,"[sangoma, psytrance, psychedelic trance, darkp...",PT7M24S,2d,hd,1525,53,[],0,1
362,oJJ4toI_yn0,J-ANmup8SchcYFA8AjtoRr-rJkc,Egon's Embrace - Sleight of Hand,UC1J5I46pnK6ZsyMADVr0zYw,Sangoma Records,2019-12-06T07:44:56Z,Subscribe: http://bit.ly/SubscribeSangoma\nVA ...,10,"[sangoma, psytrance, psychedelic trance, darkp...",PT9M44S,2d,hd,2039,72,[],0,4

use https://github.com/ytdl-org/youtube-dl to download the audio

In [ ]:
f'http://www.youtube.com/watch?v={df.loc[0].id}'

'http://www.youtube.com/watch?v=y9k55TGBZXk'

In [ ]:
download_folder = 'D:\sound\youtube'

In [ ]:
import yt_dlp

ydl_opts = {
    'outtmpl': os.path.join(download_folder,'%(title)s %(id)s.%(ext)s'), 
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '192',
    }],
}
ydl = yt_dlp.YoutubeDL(ydl_opts)
watch_url = 'http://www.youtube.com/watch?v='
rows_to_download = df

In [ ]:
def remove_existing(df):
    rows = df.apply(lambda row: not os.path.exists(os.path.join(download_folder,f'{row.title} {row.id}.mp3')),axis=1)
    return df[rows]

rows_to_download = remove_existing(rows_to_download)
display(rows_to_download.size)
rows_to_download.head()

4182

,id,etag,title,channelId,channelTitle,publishedAt,description,categoryId,tags,duration,dimension,definition,viewCount,likeCount,dislikeCount,favoriteCount,commentCount
117,y9I61a1bYyE,Yhw4pUhokJBxnuqva-nSonOGA1k,Earthling & Overload - Son of a Glitch,UC1J5I46pnK6ZsyMADVr0zYw,Sangoma Records,2022-07-06T13:22:12Z,Subscribe: http://bit.ly/SubscribeSangoma\nBuy...,10,"[sangoma, psytrance, psychedelic trance, darkp...",PT6M26S,2d,hd,1659,72,[],0,2
118,uoWEavMLvGE,hRPSx9kpTAhR9HgqjksgLqmz4VI,Ingrained Instincts - Just a Ride (Daksinamurt...,UC1J5I46pnK6ZsyMADVr0zYw,Sangoma Records,2022-07-06T13:22:19Z,Subscribe: http://bit.ly/SubscribeSangoma\nBuy...,10,"[sangoma, psytrance, psychedelic trance, darkp...",PT8M10S,2d,hd,2403,88,[],0,1
119,7wgmZ_pBGl4,wlnR8KLSZgV8pmZmzmpTyGpK4mQ,Jumpstreet - Groovegasm,UC1J5I46pnK6ZsyMADVr0zYw,Sangoma Records,2022-07-06T13:22:22Z,Subscribe: http://bit.ly/SubscribeSangoma\nBuy...,10,"[sangoma, psytrance, psychedelic trance, darkp...",PT6M48S,2d,hd,1867,75,[],0,4
120,nlKmOh2gZRI,nLTOt_5w7rGyD_AJwldW0j9_ZCk,Shenanigan - Bananigan,UC1J5I46pnK6ZsyMADVr0zYw,Sangoma Records,2022-07-06T13:22:24Z,Subscribe: http://bit.ly/SubscribeSangoma\nBuy...,10,"[sangoma, psytrance, psychedelic trance, darkp...",PT6M15S,2d,hd,1766,65,[],0,2
121,vncuC8SO33Q,Dko8kK3SAR-hl4unOTkgnQ36GRc,Black Noise & Neuromotor - Never Surrender,UC1J5I46pnK6ZsyMADVr0zYw,Sangoma Records,2022-07-06T13:22:27Z,Subscribe: http://bit.ly/SubscribeSangoma\nBuy...,10,"[sangoma, psytrance, psychedelic trance, darkp...",PT8M18S,2d,hd,1579,81,[],0,1

In [ ]:
with ydl:
    while rows_to_download.size > 0:
        rows_to_download = remove_existing(rows_to_download)
        try:
            result = ydl.download(rows_to_download.id.apply(lambda id: watch_url+id)    )
        except yt_dlp.DownloadError:
            pass
        except:
            break

[youtube] Extracting URL: http://www.youtube.com/watch?v=y9I61a1bYyE
[youtube] y9I61a1bYyE: Downloading webpage
[youtube] y9I61a1bYyE: Downloading android player API JSON
[info] y9I61a1bYyE: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Earthling & Overload - Son of a Glitch y9I61a1bYyE.webm
[download] 100% of    6.46MiB in 00:00:00 at 13.13MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Earthling & Overload - Son of a Glitch y9I61a1bYyE.mp3
Deleting original file D:\sound\youtube\Earthling & Overload - Son of a Glitch y9I61a1bYyE.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=uoWEavMLvGE
[youtube] uoWEavMLvGE: Downloading webpage
[youtube] uoWEavMLvGE: Downloading android player API JSON
[info] uoWEavMLvGE: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Ingrained Instincts - Just a Ride (Daksinamurti Remix) uoWEavMLvGE.webm
[download] 100% of    7.97MiB in 00:00:00 at 9.22MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Ingrained Instincts - Just a Ride (Daksinamurti Remix) uoWEavMLvGE.mp3
Deleting original file D:\sound\youtube\Ingrained Instincts - Just a Ride (Daksinamurti Remix) uoWEavMLvGE.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=7wgmZ_pBGl4
[youtube] 7wgmZ_pBGl4: Downloading webpage
[youtube] 7wgmZ_pBGl4: Downloading android player API JSON
[info] 7wgmZ_pBGl4: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Jumpstreet - Groovegasm 7wgmZ_pBGl4.webm
[download] 100% of    6.40MiB in 00:00:00 at 7.60MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Jumpstreet - Groovegasm 7wgmZ_pBGl4.mp3
Deleting original file D:\sound\youtube\Jumpstreet - Groovegasm 7wgmZ_pBGl4.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=nlKmOh2gZRI
[youtube] nlKmOh2gZRI: Downloading webpage
[youtube] nlKmOh2gZRI: Downloading android player API JSON
[info] nlKmOh2gZRI: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Shenanigan - Bananigan nlKmOh2gZRI.webm
[download] 100% of    6.10MiB in 00:00:01 at 4.29MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Shenanigan - Bananigan nlKmOh2gZRI.mp3
Deleting original file D:\sound\youtube\Shenanigan - Bananigan nlKmOh2gZRI.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=vncuC8SO33Q
[youtube] vncuC8SO33Q: Downloading webpage
[youtube] vncuC8SO33Q: Downloading android player API JSON
[info] vncuC8SO33Q: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Black Noise & Neuromotor - Never Surrender vncuC8SO33Q.webm
[download] 100% of    8.64MiB in 00:00:00 at 12.29MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Black Noise & Neuromotor - Never Surrender vncuC8SO33Q.mp3
Deleting original file D:\sound\youtube\Black Noise & Neuromotor - Never Surrender vncuC8SO33Q.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=PRC3TrTFRDc
[youtube] PRC3TrTFRDc: Downloading webpage
[youtube] PRC3TrTFRDc: Downloading android player API JSON
[info] PRC3TrTFRDc: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Module Virus & R2 - Fuzzy Little Rabbit PRC3TrTFRDc.webm
[download] 100% of    7.23MiB in 00:00:01 at 6.83MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Module Virus & R2 - Fuzzy Little Rabbit PRC3TrTFRDc.mp3
Deleting original file D:\sound\youtube\Module Virus & R2 - Fuzzy Little Rabbit PRC3TrTFRDc.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Sc_3RHmBvFk
[youtube] Sc_3RHmBvFk: Downloading webpage
[youtube] Sc_3RHmBvFk: Downloading android player API JSON
[info] Sc_3RHmBvFk: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Animalien & JuanMad -  Little Pink People Sc_3RHmBvFk.webm
[download] 100% of    6.35MiB in 00:00:00 at 7.33MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Animalien & JuanMad -  Little Pink People Sc_3RHmBvFk.mp3
Deleting original file D:\sound\youtube\Animalien & JuanMad -  Little Pink People Sc_3RHmBvFk.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=qn8Bm4B8VZk
[youtube] qn8Bm4B8VZk: Downloading webpage
[youtube] qn8Bm4B8VZk: Downloading android player API JSON
[info] qn8Bm4B8VZk: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's & LabRat - Fantasia qn8Bm4B8VZk.webm
[download] 100% of    7.36MiB in 00:00:00 at 7.71MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's & LabRat - Fantasia qn8Bm4B8VZk.mp3
Deleting original file D:\sound\youtube\Doom's & LabRat - Fantasia qn8Bm4B8VZk.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=qn8Bm4B8VZk
[youtube] qn8Bm4B8VZk: Downloading webpage
[youtube] qn8Bm4B8VZk: Downloading android player API JSON
[info] qn8Bm4B8VZk: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's & LabRat - Fantasia qn8Bm4B8VZk.webm
[download] 100% of    7.36MiB in 00:00:00 at 11.67MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's & LabRat - Fantasia qn8Bm4B8VZk.mp3
Deleting original file D:\sound\youtube\Doom's & LabRat - Fantasia qn8Bm4B8VZk.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=cluah6zPN_Y
[youtube] cluah6zPN_Y: Downloading webpage
[youtube] cluah6zPN_Y: Downloading android player API JSON
[info] cluah6zPN_Y: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's - Long Time Ago cluah6zPN_Y.webm
[download] 100% of    7.18MiB in 00:00:00 at 7.70MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's - Long Time Ago cluah6zPN_Y.mp3
Deleting original file D:\sound\youtube\Doom's - Long Time Ago cluah6zPN_Y.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=FNTnNYeFLFA
[youtube] FNTnNYeFLFA: Downloading webpage
[youtube] FNTnNYeFLFA: Downloading android player API JSON
[info] FNTnNYeFLFA: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's - Alchemy FNTnNYeFLFA.webm
[download] 100% of    6.92MiB in 00:00:00 at 10.23MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's - Alchemy FNTnNYeFLFA.mp3
Deleting original file D:\sound\youtube\Doom's - Alchemy FNTnNYeFLFA.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Qr5OU3tYzcQ
[youtube] Qr5OU3tYzcQ: Downloading webpage
[youtube] Qr5OU3tYzcQ: Downloading android player API JSON
[info] Qr5OU3tYzcQ: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's -  Imagination Qr5OU3tYzcQ.webm
[download] 100% of    6.96MiB in 00:00:01 at 6.12MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's -  Imagination Qr5OU3tYzcQ.mp3
Deleting original file D:\sound\youtube\Doom's -  Imagination Qr5OU3tYzcQ.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=xNl8JktK-ZI
[youtube] xNl8JktK-ZI: Downloading webpage
[youtube] xNl8JktK-ZI: Downloading android player API JSON
[info] xNl8JktK-ZI: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Daksinamurti - Hippietalamus xNl8JktK-ZI.webm
[download] 100% of    6.99MiB in 00:00:00 at 10.34MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Daksinamurti - Hippietalamus xNl8JktK-ZI.mp3
Deleting original file D:\sound\youtube\Daksinamurti - Hippietalamus xNl8JktK-ZI.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=xNl8JktK-ZI
[youtube] xNl8JktK-ZI: Downloading webpage
[youtube] xNl8JktK-ZI: Downloading android player API JSON
[info] xNl8JktK-ZI: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Daksinamurti - Hippietalamus xNl8JktK-ZI.webm
[download] 100% of    6.99MiB in 00:00:00 at 14.24MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Daksinamurti - Hippietalamus xNl8JktK-ZI.mp3
Deleting original file D:\sound\youtube\Daksinamurti - Hippietalamus xNl8JktK-ZI.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=hCBaTGTkWa4
[youtube] hCBaTGTkWa4: Downloading webpage
[youtube] hCBaTGTkWa4: Downloading android player API JSON
[info] hCBaTGTkWa4: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Babagoon - Mangalam hCBaTGTkWa4.webm
[download] 100% of    6.62MiB in 00:00:00 at 8.62MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Babagoon - Mangalam hCBaTGTkWa4.mp3
Deleting original file D:\sound\youtube\Babagoon - Mangalam hCBaTGTkWa4.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=hgMmcyPuxpw
[youtube] hgMmcyPuxpw: Downloading webpage
[youtube] hgMmcyPuxpw: Downloading android player API JSON
[info] hgMmcyPuxpw: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yabba Dabba & Doom's - Rumble Stereo hgMmcyPuxpw.webm
[download] 100% of    6.71MiB in 00:00:00 at 8.01MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yabba Dabba & Doom's - Rumble Stereo hgMmcyPuxpw.mp3
Deleting original file D:\sound\youtube\Yabba Dabba & Doom's - Rumble Stereo hgMmcyPuxpw.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=tdayel6Qq_s
[youtube] tdayel6Qq_s: Downloading webpage
[youtube] tdayel6Qq_s: Downloading android player API JSON
[info] tdayel6Qq_s: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Konebu - Ex Drummer tdayel6Qq_s.webm
[download] 100% of    7.15MiB in 00:00:00 at 7.63MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Konebu - Ex Drummer tdayel6Qq_s.mp3
Deleting original file D:\sound\youtube\Konebu - Ex Drummer tdayel6Qq_s.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=AVMLrwu0rtI
[youtube] AVMLrwu0rtI: Downloading webpage
[youtube] AVMLrwu0rtI: Downloading android player API JSON
[info] AVMLrwu0rtI: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Antonymous & Hydra-E - Circular Tweaking AVMLrwu0rtI.webm
[download] 100% of    7.15MiB in 00:00:00 at 9.02MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Antonymous & Hydra-E - Circular Tweaking AVMLrwu0rtI.mp3
Deleting original file D:\sound\youtube\Antonymous & Hydra-E - Circular Tweaking AVMLrwu0rtI.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=aNzx6rW_Jrw
[youtube] aNzx6rW_Jrw: Downloading webpage
[youtube] aNzx6rW_Jrw: Downloading android player API JSON
[info] aNzx6rW_Jrw: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yebah & Sequoya - The Endless Labyrinth aNzx6rW_Jrw.webm
[download] 100% of    7.64MiB in 00:00:00 at 8.68MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yebah & Sequoya - The Endless Labyrinth aNzx6rW_Jrw.mp3
Deleting original file D:\sound\youtube\Yebah & Sequoya - The Endless Labyrinth aNzx6rW_Jrw.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=WUijJlHnpHY
[youtube] WUijJlHnpHY: Downloading webpage
[youtube] WUijJlHnpHY: Downloading android player API JSON
[info] WUijJlHnpHY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Cyk - Ancient Symbols WUijJlHnpHY.webm
[download] 100% of    8.31MiB in 00:00:01 at 7.26MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Cyk - Ancient Symbols WUijJlHnpHY.mp3
Deleting original file D:\sound\youtube\Cyk - Ancient Symbols WUijJlHnpHY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=BVNVVfF3t0A
[youtube] BVNVVfF3t0A: Downloading webpage
[youtube] BVNVVfF3t0A: Downloading android player API JSON
[info] BVNVVfF3t0A: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Superluminal - Multi Dimensional Perception BVNVVfF3t0A.webm
[download] 100% of    8.66MiB in 00:00:00 at 12.43MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Superluminal - Multi Dimensional Perception BVNVVfF3t0A.mp3
Deleting original file D:\sound\youtube\Superluminal - Multi Dimensional Perception BVNVVfF3t0A.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=dHBYnFXgX7k
[youtube] dHBYnFXgX7k: Downloading webpage
[youtube] dHBYnFXgX7k: Downloading android player API JSON
[info] dHBYnFXgX7k: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Rezonant & Render - Make Mistake dHBYnFXgX7k.webm
[download] 100% of    7.28MiB in 00:00:01 at 6.13MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Rezonant & Render - Make Mistake dHBYnFXgX7k.mp3
Deleting original file D:\sound\youtube\Rezonant & Render - Make Mistake dHBYnFXgX7k.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=3lkvSW8dPK4
[youtube] 3lkvSW8dPK4: Downloading webpage
[youtube] 3lkvSW8dPK4: Downloading android player API JSON
[info] 3lkvSW8dPK4: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Braincell & OxyFlux - Wild Fusion 3lkvSW8dPK4.webm
[download] 100% of    6.35MiB in 00:00:00 at 8.65MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Braincell & OxyFlux - Wild Fusion 3lkvSW8dPK4.mp3
Deleting original file D:\sound\youtube\Braincell & OxyFlux - Wild Fusion 3lkvSW8dPK4.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=WN1cLnWXwoQ
[youtube] WN1cLnWXwoQ: Downloading webpage
[youtube] WN1cLnWXwoQ: Downloading android player API JSON
[info] WN1cLnWXwoQ: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Anarkick - NonLinear Creativity WN1cLnWXwoQ.webm
[download] 100% of    7.18MiB in 00:00:00 at 8.20MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Anarkick - NonLinear Creativity WN1cLnWXwoQ.mp3
Deleting original file D:\sound\youtube\Anarkick - NonLinear Creativity WN1cLnWXwoQ.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=WN1cLnWXwoQ
[youtube] WN1cLnWXwoQ: Downloading webpage
[youtube] WN1cLnWXwoQ: Downloading android player API JSON
[info] WN1cLnWXwoQ: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Anarkick - NonLinear Creativity WN1cLnWXwoQ.webm
[download] 100% of    7.18MiB in 00:00:00 at 12.92MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Anarkick - NonLinear Creativity WN1cLnWXwoQ.mp3
Deleting original file D:\sound\youtube\Anarkick - NonLinear Creativity WN1cLnWXwoQ.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=24_YV1J-Wmw
[youtube] 24_YV1J-Wmw: Downloading webpage
[youtube] 24_YV1J-Wmw: Downloading android player API JSON
[info] 24_YV1J-Wmw: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Anarkick - NonLinear Creativity (Spektron Remix) 24_YV1J-Wmw.webm
[download] 100% of    9.47MiB in 00:00:01 at 7.22MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Anarkick - NonLinear Creativity (Spektron Remix) 24_YV1J-Wmw.mp3
Deleting original file D:\sound\youtube\Anarkick - NonLinear Creativity (Spektron Remix) 24_YV1J-Wmw.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=H3FSe3T1s88
[youtube] H3FSe3T1s88: Downloading webpage
[youtube] H3FSe3T1s88: Downloading android player API JSON
[info] H3FSe3T1s88: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Anarkick - NonLinear Creativity (Wappa Remix) H3FSe3T1s88.webm
[download] 100% of    7.60MiB in 00:00:02 at 3.36MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Anarkick - NonLinear Creativity (Wappa Remix) H3FSe3T1s88.mp3
Deleting original file D:\sound\youtube\Anarkick - NonLinear Creativity (Wappa Remix) H3FSe3T1s88.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=8tI5LoFXrnA
[youtube] 8tI5LoFXrnA: Downloading webpage
[youtube] 8tI5LoFXrnA: Downloading android player API JSON
[info] 8tI5LoFXrnA: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Anarkick - NonLinear Creativity (Qwark Remix) 8tI5LoFXrnA.webm
[download] 100% of    7.56MiB in 00:00:03 at 2.16MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Anarkick - NonLinear Creativity (Qwark Remix) 8tI5LoFXrnA.mp3
Deleting original file D:\sound\youtube\Anarkick - NonLinear Creativity (Qwark Remix) 8tI5LoFXrnA.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=yzzYklZ-cW8
[youtube] yzzYklZ-cW8: Downloading webpage
[youtube] yzzYklZ-cW8: Downloading android player API JSON
[info] yzzYklZ-cW8: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Anarkick - NonLinear Creativity (Michael Crecker Remix) yzzYklZ-cW8.webm
[download] 100% of    7.41MiB in 00:00:00 at 8.28MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Anarkick - NonLinear Creativity (Michael Crecker Remix) yzzYklZ-cW8.mp3
Deleting original file D:\sound\youtube\Anarkick - NonLinear Creativity (Michael Crecker Remix) yzzYklZ-cW8.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Bc7RloQ_IFc
[youtube] Bc7RloQ_IFc: Downloading webpage
[youtube] Bc7RloQ_IFc: Downloading android player API JSON
[info] Bc7RloQ_IFc: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Anarkick - NonLinear Creativity (Creepy Deep Remix) Bc7RloQ_IFc.webm
[download] 100% of    7.79MiB in 00:00:01 at 6.05MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Anarkick - NonLinear Creativity (Creepy Deep Remix) Bc7RloQ_IFc.mp3
Deleting original file D:\sound\youtube\Anarkick - NonLinear Creativity (Creepy Deep Remix) Bc7RloQ_IFc.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=ncECgqr9iyk
[youtube] ncECgqr9iyk: Downloading webpage
[youtube] ncECgqr9iyk: Downloading android player API JSON
[info] ncECgqr9iyk: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Anarkick - NonLinear Creativity (Living Frequencies Remix) ncECgqr9iyk.webm
[download] 100% of    7.16MiB in 00:00:00 at 7.91MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Anarkick - NonLinear Creativity (Living Frequencies Remix) ncECgqr9iyk.mp3
Deleting original file D:\sound\youtube\Anarkick - NonLinear Creativity (Living Frequencies Remix) ncECgqr9iyk.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=6X8xXBSroFQ
[youtube] 6X8xXBSroFQ: Downloading webpage
[youtube] 6X8xXBSroFQ: Downloading android player API JSON
[info] 6X8xXBSroFQ: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\UkaUka - Alquimia 6X8xXBSroFQ.webm
[download] 100% of    8.63MiB in 00:00:01 at 8.44MiB/s
[ExtractAudio] Destination: D:\sound\youtube\UkaUka - Alquimia 6X8xXBSroFQ.mp3
Deleting original file D:\sound\youtube\UkaUka - Alquimia 6X8xXBSroFQ.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=6X8xXBSroFQ
[youtube] 6X8xXBSroFQ: Downloading webpage
[youtube] 6X8xXBSroFQ: Downloading android player API JSON
[info] 6X8xXBSroFQ: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\UkaUka - Alquimia 6X8xXBSroFQ.webm
[download] 100% of    8.63MiB in 00:00:00 at 15.65MiB/s
[ExtractAudio] Destination: D:\sound\youtube\UkaUka - Alquimia 6X8xXBSroFQ.mp3
Deleting original file D:\sound\youtube\UkaUka - Alquimia 6X8xXBSroFQ.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=w4hX1kfH8zI
[youtube] w4hX1kfH8zI: Downloading webpage
[youtube] w4hX1kfH8zI: Downloading android player API JSON
[info] w4hX1kfH8zI: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\UkaUka & Gizmo - Ingreedients w4hX1kfH8zI.webm
[download] 100% of    7.01MiB in 00:00:01 at 5.53MiB/s
[ExtractAudio] Destination: D:\sound\youtube\UkaUka & Gizmo - Ingreedients w4hX1kfH8zI.mp3
Deleting original file D:\sound\youtube\UkaUka & Gizmo - Ingreedients w4hX1kfH8zI.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=vHjFFQM7bLY
[youtube] vHjFFQM7bLY: Downloading webpage
[youtube] vHjFFQM7bLY: Downloading android player API JSON
[info] vHjFFQM7bLY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\UkaUka & Psique - Jumble vHjFFQM7bLY.webm
[download] 100% of    7.96MiB in 00:00:01 at 7.48MiB/s
[ExtractAudio] Destination: D:\sound\youtube\UkaUka & Psique - Jumble vHjFFQM7bLY.mp3

[download] Got error: <urlopen error timed out>

[youtube] Extracting URL: http://www.youtube.com/watch?v=ZeAaJwy3pbg
[youtube] ZeAaJwy3pbg: Downloading webpage
[youtube] ZeAaJwy3pbg: Downloading android player API JSON
[info] ZeAaJwy3pbg: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Konebu - Glimpse to the Future ZeAaJwy3pbg.webm
[download] 100% of    6.76MiB in 00:00:00 at 10.46MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Konebu - Glimpse to the Future ZeAaJwy3pbg.mp3
Deleting original file D:\sound\youtube\Konebu - Glimpse to the Future ZeAaJwy3pbg.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=LONdcroccw4
[youtube] LONdcroccw4: Downloading webpage
[youtube] LONdcroccw4: Downloading android player API JSON
[info] LONdcroccw4: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Konebu - Psychedelic Solution LONdcroccw4.webm
[download] 100% of    6.85MiB in 00:00:00 at 7.16MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Konebu - Psychedelic Solution LONdcroccw4.mp3
Deleting original file D:\sound\youtube\Konebu - Psychedelic Solution LONdcroccw4.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=YvebwJH5MMU
[youtube] YvebwJH5MMU: Downloading webpage
[youtube] YvebwJH5MMU: Downloading android player API JSON
[info] YvebwJH5MMU: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Konebu - Inception YvebwJH5MMU.webm
[download] 100% of    7.17MiB in 00:00:00 at 7.77MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Konebu - Inception YvebwJH5MMU.mp3
Deleting original file D:\sound\youtube\Konebu - Inception YvebwJH5MMU.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=2Fr9BwKoZts
[youtube] 2Fr9BwKoZts: Downloading webpage
[youtube] 2Fr9BwKoZts: Downloading android player API JSON
[info] 2Fr9BwKoZts: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Anarkick & Atbloom - Anaconda 2Fr9BwKoZts.webm
[download] 100% of    7.85MiB in 00:00:00 at 7.86MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Anarkick & Atbloom - Anaconda 2Fr9BwKoZts.mp3
Deleting original file D:\sound\youtube\Anarkick & Atbloom - Anaconda 2Fr9BwKoZts.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=2Fr9BwKoZts
[youtube] 2Fr9BwKoZts: Downloading webpage
[youtube] 2Fr9BwKoZts: Downloading android player API JSON
[info] 2Fr9BwKoZts: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Anarkick & Atbloom - Anaconda 2Fr9BwKoZts.webm
[download] 100% of    7.85MiB in 00:00:00 at 12.62MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Anarkick & Atbloom - Anaconda 2Fr9BwKoZts.mp3
Deleting original file D:\sound\youtube\Anarkick & Atbloom - Anaconda 2Fr9BwKoZts.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=EVdx5UnoqRw
[youtube] EVdx5UnoqRw: Downloading webpage
[youtube] EVdx5UnoqRw: Downloading android player API JSON
[info] EVdx5UnoqRw: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Anarkick - Life Engine EVdx5UnoqRw.webm
[download] 100% of    7.39MiB in 00:00:00 at 7.95MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Anarkick - Life Engine EVdx5UnoqRw.mp3
Deleting original file D:\sound\youtube\Anarkick - Life Engine EVdx5UnoqRw.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=M1A7vduaq28
[youtube] M1A7vduaq28: Downloading webpage
[youtube] M1A7vduaq28: Downloading android player API JSON
[info] M1A7vduaq28: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Anarkick - KarmaSutra M1A7vduaq28.webm
[download] 100% of    7.39MiB in 00:00:01 at 7.39MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Anarkick - KarmaSutra M1A7vduaq28.mp3
Deleting original file D:\sound\youtube\Anarkick - KarmaSutra M1A7vduaq28.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=YWDiA_gEC24
[youtube] YWDiA_gEC24: Downloading webpage
[youtube] YWDiA_gEC24: Downloading android player API JSON
[info] YWDiA_gEC24: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Anarkick & Juanmad - Here for Music YWDiA_gEC24.webm
[download] 100% of    7.81MiB in 00:00:00 at 8.55MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Anarkick & Juanmad - Here for Music YWDiA_gEC24.mp3
Deleting original file D:\sound\youtube\Anarkick & Juanmad - Here for Music YWDiA_gEC24.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=sRFEZMy2uU0
[youtube] sRFEZMy2uU0: Downloading webpage
[youtube] sRFEZMy2uU0: Downloading android player API JSON
[info] sRFEZMy2uU0: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Fungus Funk & Rugrats - Buenas Noches sRFEZMy2uU0.webm
[download] 100% of    7.71MiB in 00:00:00 at 10.48MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Fungus Funk & Rugrats - Buenas Noches sRFEZMy2uU0.mp3
Deleting original file D:\sound\youtube\Fungus Funk & Rugrats - Buenas Noches sRFEZMy2uU0.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=sRFEZMy2uU0
[youtube] sRFEZMy2uU0: Downloading webpage
[youtube] sRFEZMy2uU0: Downloading android player API JSON
[info] sRFEZMy2uU0: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Fungus Funk & Rugrats - Buenas Noches sRFEZMy2uU0.webm
[download] 100% of    7.71MiB in 00:00:00 at 14.14MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Fungus Funk & Rugrats - Buenas Noches sRFEZMy2uU0.mp3
Deleting original file D:\sound\youtube\Fungus Funk & Rugrats - Buenas Noches sRFEZMy2uU0.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=ThJZLML77Pc
[youtube] ThJZLML77Pc: Downloading webpage
[youtube] ThJZLML77Pc: Downloading android player API JSON
[info] ThJZLML77Pc: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Fungus Funk & Endeavour - Grateful Funk ThJZLML77Pc.webm
[download] 100% of    7.42MiB in 00:00:00 at 10.02MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Fungus Funk & Endeavour - Grateful Funk ThJZLML77Pc.mp3
Deleting original file D:\sound\youtube\Fungus Funk & Endeavour - Grateful Funk ThJZLML77Pc.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=NmSZZ0p_kzk
[youtube] NmSZZ0p_kzk: Downloading webpage
[youtube] NmSZZ0p_kzk: Downloading android player API JSON
[info] NmSZZ0p_kzk: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Fungus Funk & Hujaboy - Still Dreaming NmSZZ0p_kzk.webm
[download] 100% of    7.72MiB in 00:00:00 at 10.04MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Fungus Funk & Hujaboy - Still Dreaming NmSZZ0p_kzk.mp3
Deleting original file D:\sound\youtube\Fungus Funk & Hujaboy - Still Dreaming NmSZZ0p_kzk.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=2lGMEV0jB_M
[youtube] 2lGMEV0jB_M: Downloading webpage
[youtube] 2lGMEV0jB_M: Downloading android player API JSON
[info] 2lGMEV0jB_M: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Bubbleguns - Reset Preset 2lGMEV0jB_M.webm
[download] 100% of    8.22MiB in 00:00:01 at 7.92MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Bubbleguns - Reset Preset 2lGMEV0jB_M.mp3
Deleting original file D:\sound\youtube\Bubbleguns - Reset Preset 2lGMEV0jB_M.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=2lGMEV0jB_M
[youtube] 2lGMEV0jB_M: Downloading webpage
[youtube] 2lGMEV0jB_M: Downloading android player API JSON
[info] 2lGMEV0jB_M: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Bubbleguns - Reset Preset 2lGMEV0jB_M.webm
[download] 100% of    8.22MiB in 00:00:00 at 11.57MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Bubbleguns - Reset Preset 2lGMEV0jB_M.mp3
Deleting original file D:\sound\youtube\Bubbleguns - Reset Preset 2lGMEV0jB_M.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=oxp5c3ipdn8
[youtube] oxp5c3ipdn8: Downloading webpage
[youtube] oxp5c3ipdn8: Downloading android player API JSON
[info] oxp5c3ipdn8: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Purist, Cosinus & Sequoya - Good Mood Paradigm oxp5c3ipdn8.webm
[download] 100% of   10.05MiB in 00:00:01 at 6.88MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Purist, Cosinus & Sequoya - Good Mood Paradigm oxp5c3ipdn8.mp3
Deleting original file D:\sound\youtube\Purist, Cosinus & Sequoya - Good Mood Paradigm oxp5c3ipdn8.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=2ejDQ1dspEE
[youtube] 2ejDQ1dspEE: Downloading webpage
[youtube] 2ejDQ1dspEE: Downloading android player API JSON
[info] 2ejDQ1dspEE: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Cracked Nozes & Atropp - Anaesthesia 2ejDQ1dspEE.webm
[download] 100% of    6.71MiB in 00:00:00 at 6.97MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Cracked Nozes & Atropp - Anaesthesia 2ejDQ1dspEE.mp3
Deleting original file D:\sound\youtube\Cracked Nozes & Atropp - Anaesthesia 2ejDQ1dspEE.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=zAca-ahjAD8
[youtube] zAca-ahjAD8: Downloading webpage
[youtube] zAca-ahjAD8: Downloading android player API JSON
[info] zAca-ahjAD8: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Anarkick - Voltage Controlled Villain zAca-ahjAD8.webm
[download] 100% of    7.76MiB in 00:00:00 at 9.34MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Anarkick - Voltage Controlled Villain zAca-ahjAD8.mp3
Deleting original file D:\sound\youtube\Anarkick - Voltage Controlled Villain zAca-ahjAD8.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=UjK-xbmOfMM
[youtube] UjK-xbmOfMM: Downloading webpage
[youtube] UjK-xbmOfMM: Downloading android player API JSON
[info] UjK-xbmOfMM: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Gandhabba & Synthetik Chaos - Casual Healings UjK-xbmOfMM.webm
[download] 100% of    7.35MiB in 00:00:00 at 7.70MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Gandhabba & Synthetik Chaos - Casual Healings UjK-xbmOfMM.mp3
Deleting original file D:\sound\youtube\Gandhabba & Synthetik Chaos - Casual Healings UjK-xbmOfMM.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=zUXPW5QH6EE
[youtube] zUXPW5QH6EE: Downloading webpage
[youtube] zUXPW5QH6EE: Downloading android player API JSON
[info] zUXPW5QH6EE: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Daksinamurti - In Deep Dependance Day zUXPW5QH6EE.webm
[download] 100% of    7.71MiB in 00:00:00 at 8.87MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Daksinamurti - In Deep Dependance Day zUXPW5QH6EE.mp3
Deleting original file D:\sound\youtube\Daksinamurti - In Deep Dependance Day zUXPW5QH6EE.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=7uQWdFyVufc
[youtube] 7uQWdFyVufc: Downloading webpage
[youtube] 7uQWdFyVufc: Downloading android player API JSON
[info] 7uQWdFyVufc: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Black Noise - That's Us 7uQWdFyVufc.webm
[download] 100% of    7.06MiB in 00:00:00 at 7.63MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Black Noise - That's Us 7uQWdFyVufc.mp3
Deleting original file D:\sound\youtube\Black Noise - That's Us 7uQWdFyVufc.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=PByIhnDVahE
[youtube] PByIhnDVahE: Downloading webpage
[youtube] PByIhnDVahE: Downloading android player API JSON
[info] PByIhnDVahE: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Animalien - Garden of Weeden (Lakitu Remix) PByIhnDVahE.webm
[download] 100% of    6.76MiB in 00:00:00 at 7.01MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Animalien - Garden of Weeden (Lakitu Remix) PByIhnDVahE.mp3
Deleting original file D:\sound\youtube\Animalien - Garden of Weeden (Lakitu Remix) PByIhnDVahE.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=yBNQKX5brac
[youtube] yBNQKX5brac: Downloading webpage
[youtube] yBNQKX5brac: Downloading android player API JSON
[info] yBNQKX5brac: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Analog Anarchists (Kabayun & Cosinus) - Future Procrastination yBNQKX5brac.webm
[download] 100% of    7.77MiB in 00:00:00 at 8.29MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Analog Anarchists (Kabayun & Cosinus) - Future Procrastination yBNQKX5brac.mp3
Deleting original file D:\sound\youtube\Analog Anarchists (Kabayun & Cosinus) - Future Procrastination yBNQKX5brac.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Re6LCpN-ilA
[youtube] Re6LCpN-ilA: Downloading webpage
[youtube] Re6LCpN-ilA: Downloading android player API JSON
[info] Re6LCpN-ilA: Downloading 1 format(s): 251

[download] Got error: <urlopen error timed out>

[youtube] Extracting URL: http://www.youtube.com/watch?v=Re6LCpN-ilA
[youtube] Re6LCpN-ilA: Downloading webpage
[youtube] Re6LCpN-ilA: Downloading android player API JSON
[info] Re6LCpN-ilA: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Elf De La Nooi - Sacred Geometry Re6LCpN-ilA.webm
[download] 100% of    7.89MiB in 00:00:00 at 12.35MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Elf De La Nooi - Sacred Geometry Re6LCpN-ilA.mp3
Deleting original file D:\sound\youtube\Elf De La Nooi - Sacred Geometry Re6LCpN-ilA.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=qgqAU-FEthE
[youtube] qgqAU-FEthE: Downloading webpage
[youtube] qgqAU-FEthE: Downloading android player API JSON
[info] qgqAU-FEthE: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yabba Dabba & Make Sense - No Name, No Fame qgqAU-FEthE.webm
[download] 100% of    7.01MiB in 00:00:01 at 6.65MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yabba Dabba & Make Sense - No Name, No Fame qgqAU-FEthE.mp3
Deleting original file D:\sound\youtube\Yabba Dabba & Make Sense - No Name, No Fame qgqAU-FEthE.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=qgqAU-FEthE
[youtube] qgqAU-FEthE: Downloading webpage
[youtube] qgqAU-FEthE: Downloading android player API JSON
[info] qgqAU-FEthE: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yabba Dabba & Make Sense - No Name, No Fame qgqAU-FEthE.webm
[download] 100% of    7.01MiB in 00:00:00 at 13.62MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yabba Dabba & Make Sense - No Name, No Fame qgqAU-FEthE.mp3
Deleting original file D:\sound\youtube\Yabba Dabba & Make Sense - No Name, No Fame qgqAU-FEthE.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=VnmsNos3f3o
[youtube] VnmsNos3f3o: Downloading webpage
[youtube] VnmsNos3f3o: Downloading android player API JSON
[info] VnmsNos3f3o: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yabba Dabba & Critter - Weird by Nature VnmsNos3f3o.webm
[download] 100% of    7.28MiB in 00:00:00 at 9.35MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yabba Dabba & Critter - Weird by Nature VnmsNos3f3o.mp3
Deleting original file D:\sound\youtube\Yabba Dabba & Critter - Weird by Nature VnmsNos3f3o.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=xkSK3LHSCRE
[youtube] xkSK3LHSCRE: Downloading webpage
[youtube] xkSK3LHSCRE: Downloading android player API JSON
[info] xkSK3LHSCRE: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yabba Dabba & The Horrids - Christalooser xkSK3LHSCRE.webm
[download] 100% of    8.56MiB in 00:00:01 at 7.17MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yabba Dabba & The Horrids - Christalooser xkSK3LHSCRE.mp3
Deleting original file D:\sound\youtube\Yabba Dabba & The Horrids - Christalooser xkSK3LHSCRE.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=dzP2XK4pZh4
[youtube] dzP2XK4pZh4: Downloading webpage
[youtube] dzP2XK4pZh4: Downloading android player API JSON
[info] dzP2XK4pZh4: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yabba Dabba & Cyk - Rebirth Ceremony dzP2XK4pZh4.webm
[download] 100% of    8.46MiB in 00:00:00 at 13.95MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yabba Dabba & Cyk - Rebirth Ceremony dzP2XK4pZh4.mp3
Deleting original file D:\sound\youtube\Yabba Dabba & Cyk - Rebirth Ceremony dzP2XK4pZh4.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=VKlf8uE81gI
[youtube] VKlf8uE81gI: Downloading webpage
[youtube] VKlf8uE81gI: Downloading android player API JSON
[info] VKlf8uE81gI: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Sequoya & Hydra-E - Yes, We Bleep VKlf8uE81gI.webm
[download] 100% of    9.43MiB in 00:00:01 at 6.22MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Sequoya & Hydra-E - Yes, We Bleep VKlf8uE81gI.mp3
Deleting original file D:\sound\youtube\Sequoya & Hydra-E - Yes, We Bleep VKlf8uE81gI.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=VKlf8uE81gI
[youtube] VKlf8uE81gI: Downloading webpage
[youtube] VKlf8uE81gI: Downloading android player API JSON
[info] VKlf8uE81gI: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Sequoya & Hydra-E - Yes, We Bleep VKlf8uE81gI.webm
[download] 100% of    9.43MiB in 00:00:00 at 13.97MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Sequoya & Hydra-E - Yes, We Bleep VKlf8uE81gI.mp3
Deleting original file D:\sound\youtube\Sequoya & Hydra-E - Yes, We Bleep VKlf8uE81gI.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=BbECXUiQrP0
[youtube] BbECXUiQrP0: Downloading webpage
[youtube] BbECXUiQrP0: Downloading android player API JSON

WARNING: [youtube] BbECXUiQrP0: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = DaTJUmVCCxfc_sRnrF9 ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] BbECXUiQrP0: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Gaspard - Don't be a Qunt BbECXUiQrP0.webm
[download] 100% of    8.26MiB in 00:00:00 at 9.00MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Gaspard - Don't be a Qunt BbECXUiQrP0.mp3
Deleting original file D:\sound\youtube\Gaspard - Don't be a Qunt BbECXUiQrP0.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=LezXL1-GXqU
[youtube] LezXL1-GXqU: Downloading webpage
[youtube] LezXL1-GXqU: Downloading android player API JSON
[info] LezXL1-GXqU: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Cosinus - The Law of Evolution LezXL1-GXqU.webm
[download] 100% of    9.09MiB in 00:00:00 at 9.89MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Cosinus - The Law of Evolution LezXL1-GXqU.mp3
Deleting original file D:\sound\youtube\Cosinus - The Law of Evolution LezXL1-GXqU.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=7N8bIg8F8BY
[youtube] 7N8bIg8F8BY: Downloading webpage
[youtube] 7N8bIg8F8BY: Downloading android player API JSON
[info] 7N8bIg8F8BY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Lemurians & StomPsy - Chunky Monkey 7N8bIg8F8BY.webm
[download] 100% of    7.14MiB in 00:00:00 at 7.88MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Lemurians & StomPsy - Chunky Monkey 7N8bIg8F8BY.mp3
Deleting original file D:\sound\youtube\Lemurians & StomPsy - Chunky Monkey 7N8bIg8F8BY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=3i7rrZmVEdI
[youtube] 3i7rrZmVEdI: Downloading webpage
[youtube] 3i7rrZmVEdI: Downloading android player API JSON
[info] 3i7rrZmVEdI: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Anarkick - VB-1-Kenobi 3i7rrZmVEdI.webm
[download] 100% of    7.38MiB in 00:00:00 at 7.82MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Anarkick - VB-1-Kenobi 3i7rrZmVEdI.mp3
Deleting original file D:\sound\youtube\Anarkick - VB-1-Kenobi 3i7rrZmVEdI.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=UsXsunf_2zA
[youtube] UsXsunf_2zA: Downloading webpage
[youtube] UsXsunf_2zA: Downloading android player API JSON
[info] UsXsunf_2zA: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Antonymous & Kabayun - Fragments of Imagination UsXsunf_2zA.webm
[download] 100% of    7.45MiB in 00:00:00 at 9.92MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Antonymous & Kabayun - Fragments of Imagination UsXsunf_2zA.mp3
Deleting original file D:\sound\youtube\Antonymous & Kabayun - Fragments of Imagination UsXsunf_2zA.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=iEQxu8vp3nU
[youtube] iEQxu8vp3nU: Downloading webpage
[youtube] iEQxu8vp3nU: Downloading android player API JSON
[info] iEQxu8vp3nU: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yebah & Yabba Dabba - Leave a Leaf iEQxu8vp3nU.webm
[download] 100% of    7.00MiB in 00:00:00 at 8.99MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yebah & Yabba Dabba - Leave a Leaf iEQxu8vp3nU.mp3
Deleting original file D:\sound\youtube\Yebah & Yabba Dabba - Leave a Leaf iEQxu8vp3nU.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=wn8fSwrhu70
[youtube] wn8fSwrhu70: Downloading webpage
[youtube] wn8fSwrhu70: Downloading android player API JSON
[info] wn8fSwrhu70: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Konebu Vs Daksinamurti - No Moon wn8fSwrhu70.webm
[download] 100% of    8.26MiB in 00:00:00 at 9.51MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Konebu Vs Daksinamurti - No Moon wn8fSwrhu70.mp3
Deleting original file D:\sound\youtube\Konebu Vs Daksinamurti - No Moon wn8fSwrhu70.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=bPT88WoCSZA
[youtube] bPT88WoCSZA: Downloading webpage
[youtube] bPT88WoCSZA: Downloading android player API JSON
[info] bPT88WoCSZA: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Peyotes - Problem Child bPT88WoCSZA.webm
[download] 100% of    7.51MiB in 00:00:00 at 9.29MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Peyotes - Problem Child bPT88WoCSZA.mp3
Deleting original file D:\sound\youtube\Peyotes - Problem Child bPT88WoCSZA.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=R-Gt_vK1Luc
[youtube] R-Gt_vK1Luc: Downloading webpage
[youtube] R-Gt_vK1Luc: Downloading android player API JSON
[info] R-Gt_vK1Luc: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Ingrained Instincts - Cognitive Surplus R-Gt_vK1Luc.webm
[download] 100% of    7.35MiB in 00:00:00 at 9.79MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Ingrained Instincts - Cognitive Surplus R-Gt_vK1Luc.mp3
Deleting original file D:\sound\youtube\Ingrained Instincts - Cognitive Surplus R-Gt_vK1Luc.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=RhEJiXry_BM
[youtube] RhEJiXry_BM: Downloading webpage
[youtube] RhEJiXry_BM: Downloading android player API JSON
[info] RhEJiXry_BM: Downloading 1 format(s): 251

[download] Got error: <urlopen error timed out>

[youtube] Extracting URL: http://www.youtube.com/watch?v=RhEJiXry_BM
[youtube] RhEJiXry_BM: Downloading webpage
[youtube] RhEJiXry_BM: Downloading android player API JSON
[info] RhEJiXry_BM: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Diksha - Mental Connectivity RhEJiXry_BM.webm
[download] 100% of    7.60MiB in 00:00:01 at 5.50MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Diksha - Mental Connectivity RhEJiXry_BM.mp3
Deleting original file D:\sound\youtube\Diksha - Mental Connectivity RhEJiXry_BM.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=RhEJiXry_BM
[youtube] RhEJiXry_BM: Downloading webpage
[youtube] RhEJiXry_BM: Downloading android player API JSON
[info] RhEJiXry_BM: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Diksha - Mental Connectivity RhEJiXry_BM.webm
[download] 100% of    7.60MiB in 00:00:00 at 17.03MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Diksha - Mental Connectivity RhEJiXry_BM.mp3
Deleting original file D:\sound\youtube\Diksha - Mental Connectivity RhEJiXry_BM.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=A-EaS3iqGV8
[youtube] A-EaS3iqGV8: Downloading webpage
[youtube] A-EaS3iqGV8: Downloading android player API JSON
[info] A-EaS3iqGV8: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Gaspard & Diksha - Pure Maripsylia A-EaS3iqGV8.webm
[download] 100% of    7.51MiB in 00:00:01 at 5.10MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Gaspard & Diksha - Pure Maripsylia A-EaS3iqGV8.mp3
Deleting original file D:\sound\youtube\Gaspard & Diksha - Pure Maripsylia A-EaS3iqGV8.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=BTfSZ4psVkc
[youtube] BTfSZ4psVkc: Downloading webpage
[youtube] BTfSZ4psVkc: Downloading android player API JSON
[info] BTfSZ4psVkc: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Diksha & Spectral (Eclipse Echoes) - Solid Talk BTfSZ4psVkc.webm
[download] 100% of    7.41MiB in 00:00:01 at 6.84MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Diksha & Spectral (Eclipse Echoes) - Solid Talk BTfSZ4psVkc.mp3
Deleting original file D:\sound\youtube\Diksha & Spectral (Eclipse Echoes) - Solid Talk BTfSZ4psVkc.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=-JALCHRvgKY
[youtube] -JALCHRvgKY: Downloading webpage
[youtube] -JALCHRvgKY: Downloading android player API JSON
[info] -JALCHRvgKY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Diksha - Rollercoaster -JALCHRvgKY.webm
[download] 100% of    6.95MiB in 00:00:00 at 7.71MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Diksha - Rollercoaster -JALCHRvgKY.mp3
Deleting original file D:\sound\youtube\Diksha - Rollercoaster -JALCHRvgKY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=4f8-rxrBW6w
[youtube] 4f8-rxrBW6w: Downloading webpage
[youtube] 4f8-rxrBW6w: Downloading android player API JSON
[info] 4f8-rxrBW6w: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Fungus Funk & Diksha - New Way to Think 4f8-rxrBW6w.webm
[download] 100% of    7.13MiB in 00:00:00 at 7.94MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Fungus Funk & Diksha - New Way to Think 4f8-rxrBW6w.mp3
Deleting original file D:\sound\youtube\Fungus Funk & Diksha - New Way to Think 4f8-rxrBW6w.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=ysnZ4Hb0gKg
[youtube] ysnZ4Hb0gKg: Downloading webpage
[youtube] ysnZ4Hb0gKg: Downloading android player API JSON
[info] ysnZ4Hb0gKg: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Diksha - Teletranceport ysnZ4Hb0gKg.webm
[download] 100% of    7.02MiB in 00:00:00 at 7.30MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Diksha - Teletranceport ysnZ4Hb0gKg.mp3
Deleting original file D:\sound\youtube\Diksha - Teletranceport ysnZ4Hb0gKg.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=JdAFyhm8_eM
[youtube] JdAFyhm8_eM: Downloading webpage
[youtube] JdAFyhm8_eM: Downloading android player API JSON
[info] JdAFyhm8_eM: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Diksha - Sunny Days JdAFyhm8_eM.webm
[download] 100% of    7.09MiB in 00:00:01 at 5.37MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Diksha - Sunny Days JdAFyhm8_eM.mp3
Deleting original file D:\sound\youtube\Diksha - Sunny Days JdAFyhm8_eM.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=rWa18m1_OCY
[youtube] rWa18m1_OCY: Downloading webpage
[youtube] rWa18m1_OCY: Downloading android player API JSON
[info] rWa18m1_OCY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Diksha - Interactive Universe rWa18m1_OCY.webm
[download] 100% of    7.20MiB in 00:00:01 at 4.99MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Diksha - Interactive Universe rWa18m1_OCY.mp3
Deleting original file D:\sound\youtube\Diksha - Interactive Universe rWa18m1_OCY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=qWmuXtb8zvw
[youtube] qWmuXtb8zvw: Downloading webpage
[youtube] qWmuXtb8zvw: Downloading android player API JSON
[info] qWmuXtb8zvw: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Purist & Diksha - Liquid Sphere qWmuXtb8zvw.webm
[download] 100% of    7.76MiB in 00:00:01 at 5.50MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Purist & Diksha - Liquid Sphere qWmuXtb8zvw.mp3
Deleting original file D:\sound\youtube\Purist & Diksha - Liquid Sphere qWmuXtb8zvw.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=NIlQd1_z-h4
[youtube] NIlQd1_z-h4: Downloading webpage
[youtube] NIlQd1_z-h4: Downloading android player API JSON
[info] NIlQd1_z-h4: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Diksha - Selva NIlQd1_z-h4.webm
[download] 100% of    6.83MiB in 00:00:00 at 8.22MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Diksha - Selva NIlQd1_z-h4.mp3
Deleting original file D:\sound\youtube\Diksha - Selva NIlQd1_z-h4.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=LoRqoqFuBZE
[youtube] LoRqoqFuBZE: Downloading webpage
[youtube] LoRqoqFuBZE: Downloading android player API JSON

WARNING: [youtube] LoRqoqFuBZE: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = jpHtIYb6o-hGYlkvC5Y ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] LoRqoqFuBZE: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yachay & Purist - New Layers of Reality LoRqoqFuBZE.webm
[download] 100% of    8.00MiB in 00:00:00 at 9.22MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yachay & Purist - New Layers of Reality LoRqoqFuBZE.mp3
Deleting original file D:\sound\youtube\Yachay & Purist - New Layers of Reality LoRqoqFuBZE.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=LoRqoqFuBZE
[youtube] LoRqoqFuBZE: Downloading webpage
[youtube] LoRqoqFuBZE: Downloading android player API JSON

WARNING: [youtube] LoRqoqFuBZE: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = jXLKSFFQAZn6-Ea7kYv ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] LoRqoqFuBZE: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yachay & Purist - New Layers of Reality LoRqoqFuBZE.webm
[download] 100% of    8.00MiB in 00:00:00 at 13.03MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yachay & Purist - New Layers of Reality LoRqoqFuBZE.mp3
Deleting original file D:\sound\youtube\Yachay & Purist - New Layers of Reality LoRqoqFuBZE.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=l3foUjb4Q0o
[youtube] l3foUjb4Q0o: Downloading webpage
[youtube] l3foUjb4Q0o: Downloading android player API JSON
[info] l3foUjb4Q0o: Downloading 1 format(s): 251

[download] Got error: <urlopen error timed out>

[youtube] Extracting URL: http://www.youtube.com/watch?v=l3foUjb4Q0o
[youtube] l3foUjb4Q0o: Downloading webpage
[youtube] l3foUjb4Q0o: Downloading android player API JSON
[info] l3foUjb4Q0o: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Purist - Apometron l3foUjb4Q0o.webm
[download] 100% of    7.30MiB in 00:00:01 at 4.77MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Purist - Apometron l3foUjb4Q0o.mp3
Deleting original file D:\sound\youtube\Purist - Apometron l3foUjb4Q0o.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=XFanhczCxJY
[youtube] XFanhczCxJY: Downloading webpage
[youtube] XFanhczCxJY: Downloading android player API JSON
[info] XFanhczCxJY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Via Axis & Purist - Unfolding Hypercubes XFanhczCxJY.webm
[download] 100% of    9.62MiB in 00:00:01 at 9.30MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Via Axis & Purist - Unfolding Hypercubes XFanhczCxJY.mp3
Deleting original file D:\sound\youtube\Via Axis & Purist - Unfolding Hypercubes XFanhczCxJY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=OidXjB8ePjU
[youtube] OidXjB8ePjU: Downloading webpage
[youtube] OidXjB8ePjU: Downloading android player API JSON
[info] OidXjB8ePjU: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Purist - Estrela da Mata OidXjB8ePjU.webm
[download] 100% of    7.57MiB in 00:00:00 at 7.88MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Purist - Estrela da Mata OidXjB8ePjU.mp3
Deleting original file D:\sound\youtube\Purist - Estrela da Mata OidXjB8ePjU.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=WG2RKMUZ-Uo
[youtube] WG2RKMUZ-Uo: Downloading webpage
[youtube] WG2RKMUZ-Uo: Downloading android player API JSON
[info] WG2RKMUZ-Uo: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\EVP & Purist - Source Field Investigation WG2RKMUZ-Uo.webm
[download] 100% of    7.58MiB in 00:00:01 at 4.75MiB/s
[ExtractAudio] Destination: D:\sound\youtube\EVP & Purist - Source Field Investigation WG2RKMUZ-Uo.mp3
Deleting original file D:\sound\youtube\EVP & Purist - Source Field Investigation WG2RKMUZ-Uo.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=mxpS6jgFn5o
[youtube] mxpS6jgFn5o: Downloading webpage
[youtube] mxpS6jgFn5o: Downloading android player API JSON
[info] mxpS6jgFn5o: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Purist - El Caapi mxpS6jgFn5o.webm
[download] 100% of    7.36MiB in 00:00:01 at 5.79MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Purist - El Caapi mxpS6jgFn5o.mp3
Deleting original file D:\sound\youtube\Purist - El Caapi mxpS6jgFn5o.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=GZ8b6XrsEv8
[youtube] GZ8b6XrsEv8: Downloading webpage
[youtube] GZ8b6XrsEv8: Downloading android player API JSON
[info] GZ8b6XrsEv8: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Kabayun & Purist - Tattwa GZ8b6XrsEv8.webm
[download] 100% of    7.48MiB in 00:00:00 at 9.74MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Kabayun & Purist - Tattwa GZ8b6XrsEv8.mp3
Deleting original file D:\sound\youtube\Kabayun & Purist - Tattwa GZ8b6XrsEv8.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=ANcPhOR2zuI
[youtube] ANcPhOR2zuI: Downloading webpage
[youtube] ANcPhOR2zuI: Downloading android player API JSON
[info] ANcPhOR2zuI: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Purist - Nirmanakayas ANcPhOR2zuI.webm
[download] 100% of    7.43MiB in 00:00:00 at 7.72MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Purist - Nirmanakayas ANcPhOR2zuI.mp3
Deleting original file D:\sound\youtube\Purist - Nirmanakayas ANcPhOR2zuI.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=W2DU7O0S4x8
[youtube] W2DU7O0S4x8: Downloading webpage
[youtube] W2DU7O0S4x8: Downloading android player API JSON
[info] W2DU7O0S4x8: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Purist - Prajapatis W2DU7O0S4x8.webm
[download] 100% of    7.64MiB in 00:00:01 at 4.92MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Purist - Prajapatis W2DU7O0S4x8.mp3
Deleting original file D:\sound\youtube\Purist - Prajapatis W2DU7O0S4x8.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=e5KIb2gsZ2o
[youtube] e5KIb2gsZ2o: Downloading webpage
[youtube] e5KIb2gsZ2o: Downloading android player API JSON
[info] e5KIb2gsZ2o: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Purist - Aumpram e5KIb2gsZ2o.webm
[download] 100% of    8.21MiB in 00:00:00 at 8.50MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Purist - Aumpram e5KIb2gsZ2o.mp3
Deleting original file D:\sound\youtube\Purist - Aumpram e5KIb2gsZ2o.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=PXFkSa9rFtQ
[youtube] PXFkSa9rFtQ: Downloading webpage
[youtube] PXFkSa9rFtQ: Downloading android player API JSON
[info] PXFkSa9rFtQ: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Lemurians & Daksinamurti - Saberstick PXFkSa9rFtQ.webm
[download] 100% of    7.17MiB in 00:00:00 at 9.15MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Lemurians & Daksinamurti - Saberstick PXFkSa9rFtQ.mp3
Deleting original file D:\sound\youtube\Lemurians & Daksinamurti - Saberstick PXFkSa9rFtQ.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=PXFkSa9rFtQ
[youtube] PXFkSa9rFtQ: Downloading webpage
[youtube] PXFkSa9rFtQ: Downloading android player API JSON
[info] PXFkSa9rFtQ: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Lemurians & Daksinamurti - Saberstick PXFkSa9rFtQ.webm
[download] 100% of    7.17MiB in 00:00:00 at 12.06MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Lemurians & Daksinamurti - Saberstick PXFkSa9rFtQ.mp3
Deleting original file D:\sound\youtube\Lemurians & Daksinamurti - Saberstick PXFkSa9rFtQ.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=_7ag02PAa30
[youtube] _7ag02PAa30: Downloading webpage
[youtube] _7ag02PAa30: Downloading android player API JSON
[info] _7ag02PAa30: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Lemurians & Daksinamurti - Animism _7ag02PAa30.webm
[download] 100% of    8.23MiB in 00:00:00 at 11.42MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Lemurians & Daksinamurti - Animism _7ag02PAa30.mp3
Deleting original file D:\sound\youtube\Lemurians & Daksinamurti - Animism _7ag02PAa30.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=FJ9lHJlroRA
[youtube] FJ9lHJlroRA: Downloading webpage
[youtube] FJ9lHJlroRA: Downloading android player API JSON
[info] FJ9lHJlroRA: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Analog Anarchists - Vulcan Logic FJ9lHJlroRA.webm
[download] 100% of    7.68MiB in 00:00:01 at 4.17MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Analog Anarchists - Vulcan Logic FJ9lHJlroRA.mp3
Deleting original file D:\sound\youtube\Analog Anarchists - Vulcan Logic FJ9lHJlroRA.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=FJ9lHJlroRA
[youtube] FJ9lHJlroRA: Downloading webpage
[youtube] FJ9lHJlroRA: Downloading android player API JSON
[info] FJ9lHJlroRA: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Analog Anarchists - Vulcan Logic FJ9lHJlroRA.webm
[download] 100% of    7.68MiB in 00:00:00 at 8.28MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Analog Anarchists - Vulcan Logic FJ9lHJlroRA.mp3
Deleting original file D:\sound\youtube\Analog Anarchists - Vulcan Logic FJ9lHJlroRA.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=GCZ1sXt6WlI
[youtube] GCZ1sXt6WlI: Downloading webpage
[youtube] GCZ1sXt6WlI: Downloading android player API JSON
[info] GCZ1sXt6WlI: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Analog Anarchists - Mycelium Spores GCZ1sXt6WlI.webm
[download] 100% of    7.18MiB in 00:00:00 at 7.97MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Analog Anarchists - Mycelium Spores GCZ1sXt6WlI.mp3
Deleting original file D:\sound\youtube\Analog Anarchists - Mycelium Spores GCZ1sXt6WlI.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=yNaHr7ZlSj8
[youtube] yNaHr7ZlSj8: Downloading webpage
[youtube] yNaHr7ZlSj8: Downloading android player API JSON
[info] yNaHr7ZlSj8: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Analog Anarchists - Beyond the Stars yNaHr7ZlSj8.webm
[download] 100% of    7.71MiB in 00:00:01 at 6.92MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Analog Anarchists - Beyond the Stars yNaHr7ZlSj8.mp3
Deleting original file D:\sound\youtube\Analog Anarchists - Beyond the Stars yNaHr7ZlSj8.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=c_W2loAKSQM
[youtube] c_W2loAKSQM: Downloading webpage
[youtube] c_W2loAKSQM: Downloading android player API JSON
[info] c_W2loAKSQM: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Egon's Embrace - A Little Larger Than The Entire Universe c_W2loAKSQM.webm
[download] 100% of    9.06MiB in 00:00:01 at 7.97MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Egon's Embrace - A Little Larger Than The Entire Universe c_W2loAKSQM.mp3
Deleting original file D:\sound\youtube\Egon's Embrace - A Little Larger Than The Entire Universe c_W2loAKSQM.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=c_W2loAKSQM
[youtube] c_W2loAKSQM: Downloading webpage
[youtube] c_W2loAKSQM: Downloading android player API JSON
[info] c_W2loAKSQM: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Egon's Embrace - A Little Larger Than The Entire Universe c_W2loAKSQM.webm
[download] 100% of    9.06MiB in 00:00:00 at 12.97MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Egon's Embrace - A Little Larger Than The Entire Universe c_W2loAKSQM.mp3
Deleting original file D:\sound\youtube\Egon's Embrace - A Little Larger Than The Entire Universe c_W2loAKSQM.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=x_qPLkLCkYQ
[youtube] x_qPLkLCkYQ: Downloading webpage
[youtube] x_qPLkLCkYQ: Downloading android player API JSON
[info] x_qPLkLCkYQ: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Egon's Embrace & Archaic - Smiling With The Mouth Of The Ocean x_qPLkLCkYQ.webm
[download] 100% of    8.82MiB in 00:00:01 at 8.63MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Egon's Embrace & Archaic - Smiling With The Mouth Of The Ocean x_qPLkLCkYQ.mp3
Deleting original file D:\sound\youtube\Egon's Embrace & Archaic - Smiling With The Mouth Of The Ocean x_qPLkLCkYQ.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=h3MAZHVsoZo
[youtube] h3MAZHVsoZo: Downloading webpage
[youtube] h3MAZHVsoZo: Downloading android player API JSON
[info] h3MAZHVsoZo: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Egon's Embrace & Sequoya - Hell Is Other People h3MAZHVsoZo.webm
[download] 100% of    8.26MiB in 00:00:00 at 11.40MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Egon's Embrace & Sequoya - Hell Is Other People h3MAZHVsoZo.mp3
Deleting original file D:\sound\youtube\Egon's Embrace & Sequoya - Hell Is Other People h3MAZHVsoZo.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=nhZoo01rpfc
[youtube] nhZoo01rpfc: Downloading webpage
[youtube] nhZoo01rpfc: Downloading android player API JSON
[info] nhZoo01rpfc: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Egon's Embrace - One Day I Will Reach Back In Unravel It All, Bit By Bit, & Recreate You From Myself nhZoo01rpfc.webm
[download] 100% of    7.96MiB in 00:00:00 at 8.80MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Egon's Embrace - One Day I Will Reach Back In Unravel It All, Bit By Bit, & Recreate You From Myself nhZoo01rpfc.mp3
Deleting original file D:\sound\youtube\Egon's Embrace - One Day I Will Reach Back In Unravel It All, Bit By Bit, & Recreate You From Myself nhZoo01rpfc.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=odD9DJzv2WQ
[youtube] odD9DJzv2WQ: Downloading webpage
[youtube] odD9DJzv2WQ: Downloading android player API JSON
[info] odD9DJzv2WQ: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Egon's Embrace -  Letting Go While Holding On odD9DJzv2WQ.webm
[download] 100% of    8.86MiB in 00:00:01 at 6.16MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Egon's Embrace -  Letting Go While Holding On odD9DJzv2WQ.mp3
Deleting original file D:\sound\youtube\Egon's Embrace -  Letting Go While Holding On odD9DJzv2WQ.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=nqxekN_Dgqo
[youtube] nqxekN_Dgqo: Downloading webpage
[youtube] nqxekN_Dgqo: Downloading android player API JSON
[info] nqxekN_Dgqo: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Egon's Embrace - Dream With Exit Wounds nqxekN_Dgqo.webm
[download] 100% of    8.60MiB in 00:00:00 at 9.22MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Egon's Embrace - Dream With Exit Wounds nqxekN_Dgqo.mp3
Deleting original file D:\sound\youtube\Egon's Embrace - Dream With Exit Wounds nqxekN_Dgqo.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=3CGXGs1PLRM
[youtube] 3CGXGs1PLRM: Downloading webpage
[youtube] 3CGXGs1PLRM: Downloading android player API JSON
[info] 3CGXGs1PLRM: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Egon's Embrace - The Shallow Drowned Lose Less Than We 3CGXGs1PLRM.webm
[download] 100% of    9.10MiB in 00:00:01 at 8.47MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Egon's Embrace - The Shallow Drowned Lose Less Than We 3CGXGs1PLRM.mp3
Deleting original file D:\sound\youtube\Egon's Embrace - The Shallow Drowned Lose Less Than We 3CGXGs1PLRM.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=vMNUtWNe354
[youtube] vMNUtWNe354: Downloading webpage
[youtube] vMNUtWNe354: Downloading android player API JSON
[info] vMNUtWNe354: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Egon's Embrace - I Solve Them All; Said The Snake vMNUtWNe354.webm
[download] 100% of    8.33MiB in 00:00:01 at 7.96MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Egon's Embrace - I Solve Them All; Said The Snake vMNUtWNe354.mp3
Deleting original file D:\sound\youtube\Egon's Embrace - I Solve Them All; Said The Snake vMNUtWNe354.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=KTpP7_5I_gE
[youtube] KTpP7_5I_gE: Downloading webpage
[youtube] KTpP7_5I_gE: Downloading android player API JSON
[info] KTpP7_5I_gE: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Egon's Embrace & Tengri - We Will Be When You Will Be No More KTpP7_5I_gE.webm
[download] 100% of    7.26MiB in 00:00:01 at 7.05MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Egon's Embrace & Tengri - We Will Be When You Will Be No More KTpP7_5I_gE.mp3
Deleting original file D:\sound\youtube\Egon's Embrace & Tengri - We Will Be When You Will Be No More KTpP7_5I_gE.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Iv71xzefhxY
[youtube] Iv71xzefhxY: Downloading webpage
[youtube] Iv71xzefhxY: Downloading android player API JSON
[info] Iv71xzefhxY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm
[download] 100% of   79.07MiB in 00:00:08 at 9.48MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.mp3
Deleting original file D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Iv71xzefhxY
[youtube] Iv71xzefhxY: Downloading webpage
[youtube] Iv71xzefhxY: Downloading android player API JSON
[info] Iv71xzefhxY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm
[download] 100% of   79.07MiB in 00:00:09 at 8.32MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.mp3
Deleting original file D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=TFXJvOpQaXA
[youtube] TFXJvOpQaXA: Downloading webpage
[youtube] TFXJvOpQaXA: Downloading android player API JSON
[info] TFXJvOpQaXA: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.webm
[download] 100% of    1.68MiB in 00:00:00 at 1.95MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.mp3
Deleting original file D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=lGo2bGWHgUk
[youtube] lGo2bGWHgUk: Downloading webpage
[youtube] lGo2bGWHgUk: Downloading android player API JSON
[info] lGo2bGWHgUk: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.webm
[download] 100% of   60.72MiB in 00:00:08 at 7.38MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.mp3
Deleting original file D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=GUsH5iX1cw0
[youtube] GUsH5iX1cw0: Downloading webpage
[youtube] GUsH5iX1cw0: Downloading android player API JSON
[info] GUsH5iX1cw0: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society [Ep.3]： Cosinus [Trailer] GUsH5iX1cw0.webm
[download] 100% of    1.23MiB in 00:00:00 at 2.21MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society [Ep.3]： Cosinus [Trailer] GUsH5iX1cw0.mp3
Deleting original file D:\sound\youtube\The Sangoma Society [Ep.3]： Cosinus [Trailer] GUsH5iX1cw0.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=SItOLqk7w0E
[youtube] SItOLqk7w0E: Downloading webpage
[youtube] SItOLqk7w0E: Downloading android player API JSON
[info] SItOLqk7w0E: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society [Ep.4]： DJ sG4rY [Trailer] SItOLqk7w0E.webm
[download] 100% of    2.72MiB in 00:00:00 at 2.96MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society [Ep.4]： DJ sG4rY [Trailer] SItOLqk7w0E.mp3
Deleting original file D:\sound\youtube\The Sangoma Society [Ep.4]： DJ sG4rY [Trailer] SItOLqk7w0E.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=ewuinhHw8ZQ
[youtube] ewuinhHw8ZQ: Downloading webpage
[youtube] ewuinhHw8ZQ: Downloading android player API JSON
[info] ewuinhHw8ZQ: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's - Dark Desires ewuinhHw8ZQ.webm
[download] 100% of    8.07MiB in 00:00:00 at 9.49MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's - Dark Desires ewuinhHw8ZQ.mp3
Deleting original file D:\sound\youtube\Doom's - Dark Desires ewuinhHw8ZQ.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=ewuinhHw8ZQ
[youtube] ewuinhHw8ZQ: Downloading webpage
[youtube] ewuinhHw8ZQ: Downloading android player API JSON
[info] ewuinhHw8ZQ: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's - Dark Desires ewuinhHw8ZQ.webm
[download] 100% of    8.07MiB in 00:00:00 at 11.89MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's - Dark Desires ewuinhHw8ZQ.mp3

WARNING: [youtube] rkgo6x1ZQjU: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = TyJdeqYeaH1kz_SqVX8 ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] rkgo6x1ZQjU: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's - Mastaba rkgo6x1ZQjU.webm
[download] 100% of    7.54MiB in 00:00:01 at 4.57MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's - Mastaba rkgo6x1ZQjU.mp3
Deleting original file D:\sound\youtube\Doom's - Mastaba rkgo6x1ZQjU.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=nO86QvVAzLc
[youtube] nO86QvVAzLc: Downloading webpage
[youtube] nO86QvVAzLc: Downloading android player API JSON
[info] nO86QvVAzLc: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's & Daksinamurti - Hangover nO86QvVAzLc.webm
[download] 100% of    6.84MiB in 00:00:01 at 6.59MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's & Daksinamurti - Hangover nO86QvVAzLc.mp3
Deleting original file D:\sound\youtube\Doom's & Daksinamurti - Hangover nO86QvVAzLc.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=wy3FlcWKvhc
[youtube] wy3FlcWKvhc: Downloading webpage
[youtube] wy3FlcWKvhc: Downloading android player API JSON
[info] wy3FlcWKvhc: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's - Life Beyond wy3FlcWKvhc.webm
[download] 100% of    6.61MiB in 00:00:01 at 6.57MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's - Life Beyond wy3FlcWKvhc.mp3
Deleting original file D:\sound\youtube\Doom's - Life Beyond wy3FlcWKvhc.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=NQuK7v_oydc
[youtube] NQuK7v_oydc: Downloading webpage
[youtube] NQuK7v_oydc: Downloading android player API JSON
[info] NQuK7v_oydc: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's - Punk Fluide NQuK7v_oydc.webm
[download] 100% of    7.50MiB in 00:00:01 at 5.96MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's - Punk Fluide NQuK7v_oydc.mp3
Deleting original file D:\sound\youtube\Doom's - Punk Fluide NQuK7v_oydc.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Hhw5dHTXR7E
[youtube] Hhw5dHTXR7E: Downloading webpage
[youtube] Hhw5dHTXR7E: Downloading android player API JSON
[info] Hhw5dHTXR7E: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Peyotes - Shatter Hhw5dHTXR7E.webm
[download] 100% of    6.51MiB in 00:00:00 at 8.28MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Peyotes - Shatter Hhw5dHTXR7E.mp3
Deleting original file D:\sound\youtube\Peyotes - Shatter Hhw5dHTXR7E.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Hhw5dHTXR7E
[youtube] Hhw5dHTXR7E: Downloading webpage
[youtube] Hhw5dHTXR7E: Downloading android player API JSON
[info] Hhw5dHTXR7E: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Peyotes - Shatter Hhw5dHTXR7E.webm
[download] 100% of    6.51MiB in 00:00:00 at 11.79MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Peyotes - Shatter Hhw5dHTXR7E.mp3
Deleting original file D:\sound\youtube\Peyotes - Shatter Hhw5dHTXR7E.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=_k-O4LaUYpY
[youtube] _k-O4LaUYpY: Downloading webpage
[youtube] _k-O4LaUYpY: Downloading android player API JSON
[info] _k-O4LaUYpY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Analog Anarchists & Daksinamurti - Alerta _k-O4LaUYpY.webm
[download] 100% of    7.14MiB in 00:00:01 at 4.65MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Analog Anarchists & Daksinamurti - Alerta _k-O4LaUYpY.mp3
Deleting original file D:\sound\youtube\Analog Anarchists & Daksinamurti - Alerta _k-O4LaUYpY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=w9zT_a3Af1U
[youtube] w9zT_a3Af1U: Downloading webpage
[youtube] w9zT_a3Af1U: Downloading android player API JSON
[info] w9zT_a3Af1U: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Sequoya - Spiral Out w9zT_a3Af1U.webm
[download] 100% of    9.43MiB in 00:00:01 at 9.17MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Sequoya - Spiral Out w9zT_a3Af1U.mp3
Deleting original file D:\sound\youtube\Sequoya - Spiral Out w9zT_a3Af1U.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=vuOe7LWlCOk
[youtube] vuOe7LWlCOk: Downloading webpage
[youtube] vuOe7LWlCOk: Downloading android player API JSON
[info] vuOe7LWlCOk: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Drip Drop & Nulla Taar - Captain Strofara vuOe7LWlCOk.webm
[download] 100% of    7.51MiB in 00:00:00 at 8.64MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Drip Drop & Nulla Taar - Captain Strofara vuOe7LWlCOk.mp3
Deleting original file D:\sound\youtube\Drip Drop & Nulla Taar - Captain Strofara vuOe7LWlCOk.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=NP3OYfUAqKY
[youtube] NP3OYfUAqKY: Downloading webpage
[youtube] NP3OYfUAqKY: Downloading android player API JSON

WARNING: [youtube] NP3OYfUAqKY: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = THgcML41SqNQxOjPeoV ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] NP3OYfUAqKY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Kabayun & Argonics - Vagator Vibes NP3OYfUAqKY.webm
[download] 100% of    7.61MiB in 00:00:00 at 9.66MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Kabayun & Argonics - Vagator Vibes NP3OYfUAqKY.mp3
Deleting original file D:\sound\youtube\Kabayun & Argonics - Vagator Vibes NP3OYfUAqKY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=HV1756ah1S4
[youtube] HV1756ah1S4: Downloading webpage
[youtube] HV1756ah1S4: Downloading android player API JSON
[info] HV1756ah1S4: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Elfdelanooi - Pharma 69 HV1756ah1S4.webm
[download] 100% of    8.46MiB in 00:00:01 at 8.24MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Elfdelanooi - Pharma 69 HV1756ah1S4.mp3
Deleting original file D:\sound\youtube\Elfdelanooi - Pharma 69 HV1756ah1S4.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=0mCuilegw-g
[youtube] 0mCuilegw-g: Downloading webpage
[youtube] 0mCuilegw-g: Downloading android player API JSON

WARNING: [youtube] 0mCuilegw-g: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = j09iVWFVDfYxNuV4N5U ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] 0mCuilegw-g: Downloading 1 format(s): 251

[download] Got error: <urlopen error timed out>

[youtube] Extracting URL: http://www.youtube.com/watch?v=Iv71xzefhxY
[youtube] Iv71xzefhxY: Downloading webpage
[youtube] Iv71xzefhxY: Downloading android player API JSON
[info] Iv71xzefhxY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm
[download] 100% of   79.07MiB in 00:00:08 at 8.96MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.mp3
Deleting original file D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Iv71xzefhxY
[youtube] Iv71xzefhxY: Downloading webpage
[youtube] Iv71xzefhxY: Downloading android player API JSON
[info] Iv71xzefhxY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm
[download] 100% of   79.07MiB in 00:00:08 at 9.77MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.mp3
Deleting original file D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=TFXJvOpQaXA
[youtube] TFXJvOpQaXA: Downloading webpage
[youtube] TFXJvOpQaXA: Downloading android player API JSON
[info] TFXJvOpQaXA: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.webm
[download] 100% of    1.68MiB in 00:00:00 at 4.66MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.mp3
Deleting original file D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=lGo2bGWHgUk
[youtube] lGo2bGWHgUk: Downloading webpage
[youtube] lGo2bGWHgUk: Downloading android player API JSON
[info] lGo2bGWHgUk: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.webm
[download] 100% of   60.72MiB in 00:00:07 at 8.55MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.mp3
Deleting original file D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=GUsH5iX1cw0
[youtube] GUsH5iX1cw0: Downloading webpage
[youtube] GUsH5iX1cw0: Downloading android player API JSON
[info] GUsH5iX1cw0: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society [Ep.3]： Cosinus [Trailer] GUsH5iX1cw0.webm
[download] 100% of    1.23MiB in 00:00:00 at 2.55MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society [Ep.3]： Cosinus [Trailer] GUsH5iX1cw0.mp3
Deleting original file D:\sound\youtube\The Sangoma Society [Ep.3]： Cosinus [Trailer] GUsH5iX1cw0.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=SItOLqk7w0E
[youtube] SItOLqk7w0E: Downloading webpage
[youtube] SItOLqk7w0E: Downloading android player API JSON
[info] SItOLqk7w0E: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society [Ep.4]： DJ sG4rY [Trailer] SItOLqk7w0E.webm
[download] 100% of    2.72MiB in 00:00:00 at 6.10MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society [Ep.4]： DJ sG4rY [Trailer] SItOLqk7w0E.mp3
Deleting original file D:\sound\youtube\The Sangoma Society [Ep.4]： DJ sG4rY [Trailer] SItOLqk7w0E.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=0mCuilegw-g
[youtube] 0mCuilegw-g: Downloading webpage
[youtube] 0mCuilegw-g: Downloading android player API JSON

WARNING: [youtube] 0mCuilegw-g: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = jhpxU49YqkJ3w3i_5CM ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] 0mCuilegw-g: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Gaspard ft. Ingrid - Datenight 0mCuilegw-g.webm
[download] 100% of    8.66MiB in 00:00:00 at 12.64MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Gaspard ft. Ingrid - Datenight 0mCuilegw-g.mp3
Deleting original file D:\sound\youtube\Gaspard ft. Ingrid - Datenight 0mCuilegw-g.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=feYjsLvpj-0
[youtube] feYjsLvpj-0: Downloading webpage
[youtube] feYjsLvpj-0: Downloading android player API JSON
[info] feYjsLvpj-0: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Berserkers (Lurker & N3xu5) - Ragnarökr feYjsLvpj-0.webm
[download] 100% of    8.40MiB in 00:00:02 at 4.18MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Berserkers (Lurker & N3xu5) - Ragnarökr feYjsLvpj-0.mp3
Deleting original file D:\sound\youtube\Berserkers (Lurker & N3xu5) - Ragnarökr feYjsLvpj-0.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=unO98UWYyvQ
[youtube] unO98UWYyvQ: Downloading webpage
[youtube] unO98UWYyvQ: Downloading android player API JSON
[info] unO98UWYyvQ: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Anarkick - Marathon unO98UWYyvQ.webm
[download] 100% of    7.19MiB in 00:00:01 at 6.88MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Anarkick - Marathon unO98UWYyvQ.mp3
Deleting original file D:\sound\youtube\Anarkick - Marathon unO98UWYyvQ.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=PhCZE1BhieA
[youtube] PhCZE1BhieA: Downloading webpage
[youtube] PhCZE1BhieA: Downloading android player API JSON

WARNING: [youtube] PhCZE1BhieA: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = jfFhvJp0aCaBwPgt0SD ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] PhCZE1BhieA: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Cosinus - Aurinko PhCZE1BhieA.webm
[download] 100% of    7.89MiB in 00:00:03 at 2.01MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Cosinus - Aurinko PhCZE1BhieA.mp3
Deleting original file D:\sound\youtube\Cosinus - Aurinko PhCZE1BhieA.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=KWeHn0hq22k
[youtube] KWeHn0hq22k: Downloading webpage
[youtube] KWeHn0hq22k: Downloading android player API JSON
[info] KWeHn0hq22k: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Superluminal - Anything Is Possible KWeHn0hq22k.webm
[download] 100% of    7.40MiB in 00:00:01 at 7.34MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Superluminal - Anything Is Possible KWeHn0hq22k.mp3
Deleting original file D:\sound\youtube\Superluminal - Anything Is Possible KWeHn0hq22k.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=KWeHn0hq22k
[youtube] KWeHn0hq22k: Downloading webpage
[youtube] KWeHn0hq22k: Downloading android player API JSON
[info] KWeHn0hq22k: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Superluminal - Anything Is Possible KWeHn0hq22k.webm
[download] 100% of    7.40MiB in 00:00:00 at 13.39MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Superluminal - Anything Is Possible KWeHn0hq22k.mp3
Deleting original file D:\sound\youtube\Superluminal - Anything Is Possible KWeHn0hq22k.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=DaCkUD61x-4
[youtube] DaCkUD61x-4: Downloading webpage
[youtube] DaCkUD61x-4: Downloading android player API JSON
[info] DaCkUD61x-4: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Superluminal - Infinite Corridor DaCkUD61x-4.webm
[download] 100% of    6.87MiB in 00:00:00 at 9.07MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Superluminal - Infinite Corridor DaCkUD61x-4.mp3
Deleting original file D:\sound\youtube\Superluminal - Infinite Corridor DaCkUD61x-4.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=ZQkrKMltJdU
[youtube] ZQkrKMltJdU: Downloading webpage
[youtube] ZQkrKMltJdU: Downloading android player API JSON
[info] ZQkrKMltJdU: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Superluminal - Different Program ZQkrKMltJdU.webm
[download] 100% of    7.96MiB in 00:00:00 at 11.99MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Superluminal - Different Program ZQkrKMltJdU.mp3
Deleting original file D:\sound\youtube\Superluminal - Different Program ZQkrKMltJdU.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=EEwm9Ih1cOI
[youtube] EEwm9Ih1cOI: Downloading webpage
[youtube] EEwm9Ih1cOI: Downloading android player API JSON
[info] EEwm9Ih1cOI: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yebah - Phenomenon EEwm9Ih1cOI.webm
[download] 100% of    7.55MiB in 00:00:00 at 11.57MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yebah - Phenomenon EEwm9Ih1cOI.mp3
Deleting original file D:\sound\youtube\Yebah - Phenomenon EEwm9Ih1cOI.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=EEwm9Ih1cOI
[youtube] EEwm9Ih1cOI: Downloading webpage
[youtube] EEwm9Ih1cOI: Downloading android player API JSON
[info] EEwm9Ih1cOI: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yebah - Phenomenon EEwm9Ih1cOI.webm
[download] 100% of    7.55MiB in 00:00:00 at 14.89MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yebah - Phenomenon EEwm9Ih1cOI.mp3
Deleting original file D:\sound\youtube\Yebah - Phenomenon EEwm9Ih1cOI.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=-XuQNSkkKac
[youtube] -XuQNSkkKac: Downloading webpage
[youtube] -XuQNSkkKac: Downloading android player API JSON
[info] -XuQNSkkKac: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yebah - Crazy Like You -XuQNSkkKac.webm
[download] 100% of    7.44MiB in 00:00:00 at 7.99MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yebah - Crazy Like You -XuQNSkkKac.mp3
Deleting original file D:\sound\youtube\Yebah - Crazy Like You -XuQNSkkKac.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=p2zgFVHpKVU
[youtube] p2zgFVHpKVU: Downloading webpage
[youtube] p2zgFVHpKVU: Downloading android player API JSON
[info] p2zgFVHpKVU: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yebah - Nebula p2zgFVHpKVU.webm
[download] 100% of    7.29MiB in 00:00:00 at 8.49MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yebah - Nebula p2zgFVHpKVU.mp3
Deleting original file D:\sound\youtube\Yebah - Nebula p2zgFVHpKVU.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=rmU5cceNM9Q
[youtube] rmU5cceNM9Q: Downloading webpage
[youtube] rmU5cceNM9Q: Downloading android player API JSON
[info] rmU5cceNM9Q: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yebah - Midnight Sorcery rmU5cceNM9Q.webm
[download] 100% of    8.47MiB in 00:00:01 at 8.00MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yebah - Midnight Sorcery rmU5cceNM9Q.mp3
Deleting original file D:\sound\youtube\Yebah - Midnight Sorcery rmU5cceNM9Q.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=FesrkuuhYXs
[youtube] FesrkuuhYXs: Downloading webpage
[youtube] FesrkuuhYXs: Downloading android player API JSON
[info] FesrkuuhYXs: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yebah - Drips Of Perception FesrkuuhYXs.webm
[download] 100% of    7.57MiB in 00:00:00 at 8.99MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yebah - Drips Of Perception FesrkuuhYXs.mp3
Deleting original file D:\sound\youtube\Yebah - Drips Of Perception FesrkuuhYXs.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=IH7OVSIXwa4
[youtube] IH7OVSIXwa4: Downloading webpage
[youtube] IH7OVSIXwa4: Downloading android player API JSON
[info] IH7OVSIXwa4: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yebah - Storm Of Creativity IH7OVSIXwa4.webm
[download] 100% of    7.26MiB in 00:00:00 at 7.48MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yebah - Storm Of Creativity IH7OVSIXwa4.mp3
Deleting original file D:\sound\youtube\Yebah - Storm Of Creativity IH7OVSIXwa4.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=1bNOdhowCCc
[youtube] 1bNOdhowCCc: Downloading webpage
[youtube] 1bNOdhowCCc: Downloading android player API JSON
[info] 1bNOdhowCCc: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yebah - Darkness Projection 1bNOdhowCCc.webm
[download] 100% of    7.46MiB in 00:00:00 at 8.09MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yebah - Darkness Projection 1bNOdhowCCc.mp3
Deleting original file D:\sound\youtube\Yebah - Darkness Projection 1bNOdhowCCc.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=GCyucSxc5tI
[youtube] GCyucSxc5tI: Downloading webpage
[youtube] GCyucSxc5tI: Downloading android player API JSON

WARNING: [youtube] GCyucSxc5tI: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = Dcf61HCCOe0lpBGo0zz ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] GCyucSxc5tI: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yebah - Facts And Theories GCyucSxc5tI.webm
[download] 100% of    7.68MiB in 00:00:00 at 8.65MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yebah - Facts And Theories GCyucSxc5tI.mp3
Deleting original file D:\sound\youtube\Yebah - Facts And Theories GCyucSxc5tI.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=_0Ya-Q8gD3M
[youtube] _0Ya-Q8gD3M: Downloading webpage
[youtube] _0Ya-Q8gD3M: Downloading android player API JSON
[info] _0Ya-Q8gD3M: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yebah - Spiritual Awakening _0Ya-Q8gD3M.webm
[download] 100% of    6.75MiB in 00:00:00 at 10.13MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yebah - Spiritual Awakening _0Ya-Q8gD3M.mp3
Deleting original file D:\sound\youtube\Yebah - Spiritual Awakening _0Ya-Q8gD3M.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=GHvNqQOz1jo
[youtube] GHvNqQOz1jo: Downloading webpage
[youtube] GHvNqQOz1jo: Downloading android player API JSON
[info] GHvNqQOz1jo: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yebah - The Dreamcatcher GHvNqQOz1jo.webm
[download] 100% of    8.04MiB in 00:00:01 at 7.58MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yebah - The Dreamcatcher GHvNqQOz1jo.mp3
Deleting original file D:\sound\youtube\Yebah - The Dreamcatcher GHvNqQOz1jo.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=YYMxUbbLncw
[youtube] YYMxUbbLncw: Downloading webpage
[youtube] YYMxUbbLncw: Downloading android player API JSON
[info] YYMxUbbLncw: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Shiibashunsuke - Metricia YYMxUbbLncw.webm
[download] 100% of    7.44MiB in 00:00:00 at 8.96MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Shiibashunsuke - Metricia YYMxUbbLncw.mp3
Deleting original file D:\sound\youtube\Shiibashunsuke - Metricia YYMxUbbLncw.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=YYMxUbbLncw
[youtube] YYMxUbbLncw: Downloading webpage
[youtube] YYMxUbbLncw: Downloading android player API JSON
[info] YYMxUbbLncw: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Shiibashunsuke - Metricia YYMxUbbLncw.webm
[download] 100% of    7.44MiB in 00:00:00 at 15.23MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Shiibashunsuke - Metricia YYMxUbbLncw.mp3
Deleting original file D:\sound\youtube\Shiibashunsuke - Metricia YYMxUbbLncw.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=ZiMeECTYyqc
[youtube] ZiMeECTYyqc: Downloading webpage
[youtube] ZiMeECTYyqc: Downloading android player API JSON
[info] ZiMeECTYyqc: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Shiibashunsuke - Bio Bit ZiMeECTYyqc.webm
[download] 100% of    8.12MiB in 00:00:01 at 7.01MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Shiibashunsuke - Bio Bit ZiMeECTYyqc.mp3
Deleting original file D:\sound\youtube\Shiibashunsuke - Bio Bit ZiMeECTYyqc.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=VUnxgFtsPEU
[youtube] VUnxgFtsPEU: Downloading webpage
[youtube] VUnxgFtsPEU: Downloading android player API JSON
[info] VUnxgFtsPEU: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Shiibashunsuke - Out Of Silence VUnxgFtsPEU.webm
[download] 100% of    7.75MiB in 00:00:00 at 9.10MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Shiibashunsuke - Out Of Silence VUnxgFtsPEU.mp3
Deleting original file D:\sound\youtube\Shiibashunsuke - Out Of Silence VUnxgFtsPEU.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=PvPZqYzdRWw
[youtube] PvPZqYzdRWw: Downloading webpage
[youtube] PvPZqYzdRWw: Downloading android player API JSON

WARNING: [youtube] PvPZqYzdRWw: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = zGTKV4KxGgR5XNeSw3U ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] PvPZqYzdRWw: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Ingrained Instincts - Atlantes PvPZqYzdRWw.webm
[download] 100% of    7.09MiB in 00:00:00 at 10.45MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Ingrained Instincts - Atlantes PvPZqYzdRWw.mp3
Deleting original file D:\sound\youtube\Ingrained Instincts - Atlantes PvPZqYzdRWw.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=PvPZqYzdRWw
[youtube] PvPZqYzdRWw: Downloading webpage
[youtube] PvPZqYzdRWw: Downloading android player API JSON

WARNING: [youtube] PvPZqYzdRWw: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = z1KxmUCFIPPm-LC5udI ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] PvPZqYzdRWw: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Ingrained Instincts - Atlantes PvPZqYzdRWw.webm
[download] 100% of    7.09MiB in 00:00:00 at 15.56MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Ingrained Instincts - Atlantes PvPZqYzdRWw.mp3
Deleting original file D:\sound\youtube\Ingrained Instincts - Atlantes PvPZqYzdRWw.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=F2s820Btvns
[youtube] F2s820Btvns: Downloading webpage
[youtube] F2s820Btvns: Downloading android player API JSON
[info] F2s820Btvns: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Jumpstreet & Mavzy - Pardon？ D’accord! F2s820Btvns.webm
[download] 100% of    6.84MiB in 00:00:00 at 9.88MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Jumpstreet & Mavzy - Pardon？ D’accord! F2s820Btvns.mp3
Deleting original file D:\sound\youtube\Jumpstreet & Mavzy - Pardon？ D’accord! F2s820Btvns.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=yttbmHmeONg
[youtube] yttbmHmeONg: Downloading webpage
[youtube] yttbmHmeONg: Downloading android player API JSON
[info] yttbmHmeONg: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Oxyflux & Render - Tridimensional Object yttbmHmeONg.webm
[download] 100% of    6.92MiB in 00:00:00 at 10.17MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Oxyflux & Render - Tridimensional Object yttbmHmeONg.mp3
Deleting original file D:\sound\youtube\Oxyflux & Render - Tridimensional Object yttbmHmeONg.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=iGztsEjb8KU
[youtube] iGztsEjb8KU: Downloading webpage
[youtube] iGztsEjb8KU: Downloading android player API JSON
[info] iGztsEjb8KU: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom’s - Metric System iGztsEjb8KU.webm
[download] 100% of    7.89MiB in 00:00:00 at 8.40MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom’s - Metric System iGztsEjb8KU.mp3
Deleting original file D:\sound\youtube\Doom’s - Metric System iGztsEjb8KU.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=ngrPqyluKMs
[youtube] ngrPqyluKMs: Downloading webpage
[youtube] ngrPqyluKMs: Downloading android player API JSON
[info] ngrPqyluKMs: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Daksinamurti - Howl ngrPqyluKMs.webm
[download] 100% of    7.53MiB in 00:00:00 at 8.44MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Daksinamurti - Howl ngrPqyluKMs.mp3
Deleting original file D:\sound\youtube\Daksinamurti - Howl ngrPqyluKMs.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=LpNvNYc-MOs
[youtube] LpNvNYc-MOs: Downloading webpage
[youtube] LpNvNYc-MOs: Downloading android player API JSON

WARNING: [youtube] LpNvNYc-MOs: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = jjZO6C5er_fCtOR048U ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] LpNvNYc-MOs: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Black Noise & Peyotes - Raw Power LpNvNYc-MOs.webm
[download] 100% of    6.90MiB in 00:00:00 at 7.46MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Black Noise & Peyotes - Raw Power LpNvNYc-MOs.mp3
Deleting original file D:\sound\youtube\Black Noise & Peyotes - Raw Power LpNvNYc-MOs.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=MF1e6uZvAf8
[youtube] MF1e6uZvAf8: Downloading webpage
[youtube] MF1e6uZvAf8: Downloading android player API JSON
[info] MF1e6uZvAf8: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Rezonant - Wake the F... Up MF1e6uZvAf8.webm
[download] 100% of    7.76MiB in 00:00:00 at 10.82MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Rezonant - Wake the F... Up MF1e6uZvAf8.mp3
Deleting original file D:\sound\youtube\Rezonant - Wake the F... Up MF1e6uZvAf8.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=ter99692JsE
[youtube] ter99692JsE: Downloading webpage
[youtube] ter99692JsE: Downloading android player API JSON
[info] ter99692JsE: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Eritas - Symptones ter99692JsE.webm
[download] 100% of    6.35MiB in 00:00:00 at 8.47MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Eritas - Symptones ter99692JsE.mp3
Deleting original file D:\sound\youtube\Eritas - Symptones ter99692JsE.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=kLvleKqbahU
[youtube] kLvleKqbahU: Downloading webpage
[youtube] kLvleKqbahU: Downloading android player API JSON
[info] kLvleKqbahU: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Mark Day & Zzbing - Psylags kLvleKqbahU.webm
[download] 100% of    8.03MiB in 00:00:01 at 7.52MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Mark Day & Zzbing - Psylags kLvleKqbahU.mp3
Deleting original file D:\sound\youtube\Mark Day & Zzbing - Psylags kLvleKqbahU.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=zaBceLcqCGE
[youtube] zaBceLcqCGE: Downloading webpage
[youtube] zaBceLcqCGE: Downloading android player API JSON
[info] zaBceLcqCGE: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Horrids - Space Builder zaBceLcqCGE.webm
[download] 100% of    8.90MiB in 00:00:01 at 8.67MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Horrids - Space Builder zaBceLcqCGE.mp3
Deleting original file D:\sound\youtube\The Horrids - Space Builder zaBceLcqCGE.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=wbSorB_vJxo
[youtube] wbSorB_vJxo: Downloading webpage
[youtube] wbSorB_vJxo: Downloading android player API JSON
[info] wbSorB_vJxo: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Kaliyuga & Dopadocks - Catoplebas wbSorB_vJxo.webm
[download] 100% of    7.37MiB in 00:00:00 at 9.07MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Kaliyuga & Dopadocks - Catoplebas wbSorB_vJxo.mp3
Deleting original file D:\sound\youtube\Kaliyuga & Dopadocks - Catoplebas wbSorB_vJxo.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=wbSorB_vJxo
[youtube] wbSorB_vJxo: Downloading webpage
[youtube] wbSorB_vJxo: Downloading android player API JSON
[info] wbSorB_vJxo: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Kaliyuga & Dopadocks - Catoplebas wbSorB_vJxo.webm
[download] 100% of    7.37MiB in 00:00:00 at 11.45MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Kaliyuga & Dopadocks - Catoplebas wbSorB_vJxo.mp3
Deleting original file D:\sound\youtube\Kaliyuga & Dopadocks - Catoplebas wbSorB_vJxo.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=vf__lkzGfnU
[youtube] vf__lkzGfnU: Downloading webpage
[youtube] vf__lkzGfnU: Downloading android player API JSON
[info] vf__lkzGfnU: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Kaliyuga & Cosinus - Baphomet Teapot vf__lkzGfnU.webm
[download] 100% of    7.58MiB in 00:00:01 at 7.48MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Kaliyuga & Cosinus - Baphomet Teapot vf__lkzGfnU.mp3
Deleting original file D:\sound\youtube\Kaliyuga & Cosinus - Baphomet Teapot vf__lkzGfnU.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=uJGHk9sr9hU
[youtube] uJGHk9sr9hU: Downloading webpage
[youtube] uJGHk9sr9hU: Downloading android player API JSON
[info] uJGHk9sr9hU: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Kaliyuga - Guadallas uJGHk9sr9hU.webm
[download] 100% of    8.03MiB in 00:00:01 at 4.36MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Kaliyuga - Guadallas uJGHk9sr9hU.mp3
Deleting original file D:\sound\youtube\Kaliyuga - Guadallas uJGHk9sr9hU.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=JXKULE6YY8c
[youtube] JXKULE6YY8c: Downloading webpage
[youtube] JXKULE6YY8c: Downloading android player API JSON

WARNING: [youtube] JXKULE6YY8c: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = ji2OcsQiZwRBICDb8rF ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] JXKULE6YY8c: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Kaliyuga & Daksinamurti - Mushkraka JXKULE6YY8c.webm
[download] 100% of    6.80MiB in 00:00:01 at 4.16MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Kaliyuga & Daksinamurti - Mushkraka JXKULE6YY8c.mp3
Deleting original file D:\sound\youtube\Kaliyuga & Daksinamurti - Mushkraka JXKULE6YY8c.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Hb73Xlmp8h8
[youtube] Hb73Xlmp8h8: Downloading webpage
[youtube] Hb73Xlmp8h8: Downloading android player API JSON
[info] Hb73Xlmp8h8: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Kaliyuga - Modular Pads Hb73Xlmp8h8.webm
[download] 100% of    7.97MiB in 00:00:00 at 8.72MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Kaliyuga - Modular Pads Hb73Xlmp8h8.mp3
Deleting original file D:\sound\youtube\Kaliyuga - Modular Pads Hb73Xlmp8h8.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=VJ7eL-H9-V0
[youtube] VJ7eL-H9-V0: Downloading webpage
[youtube] VJ7eL-H9-V0: Downloading android player API JSON
[info] VJ7eL-H9-V0: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Kaliyuga & Tskun - From Afar VJ7eL-H9-V0.webm
[download] 100% of   10.29MiB in 00:00:02 at 5.06MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Kaliyuga & Tskun - From Afar VJ7eL-H9-V0.mp3
Deleting original file D:\sound\youtube\Kaliyuga & Tskun - From Afar VJ7eL-H9-V0.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=ZaP86s25VNY
[youtube] ZaP86s25VNY: Downloading webpage
[youtube] ZaP86s25VNY: Downloading android player API JSON
[info] ZaP86s25VNY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Kaliyuga & Mikel Parvati - No Help ZaP86s25VNY.webm
[download] 100% of    5.94MiB in 00:00:00 at 6.20MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Kaliyuga & Mikel Parvati - No Help ZaP86s25VNY.mp3
Deleting original file D:\sound\youtube\Kaliyuga & Mikel Parvati - No Help ZaP86s25VNY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=sEl4Oz0RYJs
[youtube] sEl4Oz0RYJs: Downloading webpage
[youtube] sEl4Oz0RYJs: Downloading android player API JSON
[info] sEl4Oz0RYJs: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Kaliyuga & Electryxeed - Alchemical Transmutation sEl4Oz0RYJs.webm
[download] 100% of    7.14MiB in 00:00:00 at 7.18MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Kaliyuga & Electryxeed - Alchemical Transmutation sEl4Oz0RYJs.mp3
Deleting original file D:\sound\youtube\Kaliyuga & Electryxeed - Alchemical Transmutation sEl4Oz0RYJs.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=UrYNiTrMOWE
[youtube] UrYNiTrMOWE: Downloading webpage
[youtube] UrYNiTrMOWE: Downloading android player API JSON
[info] UrYNiTrMOWE: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Kaliyuga & Elf de La Nooi - Elf De La Yuga UrYNiTrMOWE.webm
[download] 100% of    7.59MiB in 00:00:00 at 8.39MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Kaliyuga & Elf de La Nooi - Elf De La Yuga UrYNiTrMOWE.mp3
Deleting original file D:\sound\youtube\Kaliyuga & Elf de La Nooi - Elf De La Yuga UrYNiTrMOWE.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=8Ur89r6QwRQ
[youtube] 8Ur89r6QwRQ: Downloading webpage
[youtube] 8Ur89r6QwRQ: Downloading android player API JSON
[info] 8Ur89r6QwRQ: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Kaliyuga - Plantas Sagradas 8Ur89r6QwRQ.webm
[download] 100% of    7.30MiB in 00:00:00 at 8.63MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Kaliyuga - Plantas Sagradas 8Ur89r6QwRQ.mp3
Deleting original file D:\sound\youtube\Kaliyuga - Plantas Sagradas 8Ur89r6QwRQ.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=OWDNUoZI0_I
[youtube] OWDNUoZI0_I: Downloading webpage
[youtube] OWDNUoZI0_I: Downloading android player API JSON

WARNING: [youtube] OWDNUoZI0_I: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = DyIugkCfcg5t13_ktPw ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] OWDNUoZI0_I: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Cosinus - Parallel Worlds OWDNUoZI0_I.webm
[download] 100% of    8.14MiB in 00:00:00 at 9.47MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Cosinus - Parallel Worlds OWDNUoZI0_I.mp3
Deleting original file D:\sound\youtube\Cosinus - Parallel Worlds OWDNUoZI0_I.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=OWDNUoZI0_I
[youtube] OWDNUoZI0_I: Downloading webpage
[youtube] OWDNUoZI0_I: Downloading android player API JSON

WARNING: [youtube] OWDNUoZI0_I: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = TR3KtxBFjTaqOIPOJQ7 ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] OWDNUoZI0_I: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Cosinus - Parallel Worlds OWDNUoZI0_I.webm
[download] 100% of    8.14MiB in 00:00:00 at 14.84MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Cosinus - Parallel Worlds OWDNUoZI0_I.mp3
Deleting original file D:\sound\youtube\Cosinus - Parallel Worlds OWDNUoZI0_I.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=hL24bVWb4J0
[youtube] hL24bVWb4J0: Downloading webpage
[youtube] hL24bVWb4J0: Downloading android player API JSON
[info] hL24bVWb4J0: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Cosinus - Sinister Shadows hL24bVWb4J0.webm
[download] 100% of    8.93MiB in 00:00:00 at 9.02MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Cosinus - Sinister Shadows hL24bVWb4J0.mp3
Deleting original file D:\sound\youtube\Cosinus - Sinister Shadows hL24bVWb4J0.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=ft7sZdVdZxE
[youtube] ft7sZdVdZxE: Downloading webpage
[youtube] ft7sZdVdZxE: Downloading android player API JSON
[info] ft7sZdVdZxE: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Cosinus & Daksinamurti  - All Things Must Pass ft7sZdVdZxE.webm
[download] 100% of    8.56MiB in 00:00:00 at 12.18MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Cosinus & Daksinamurti  - All Things Must Pass ft7sZdVdZxE.mp3
Deleting original file D:\sound\youtube\Cosinus & Daksinamurti  - All Things Must Pass ft7sZdVdZxE.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=xqUyaoFcJck
[youtube] xqUyaoFcJck: Downloading webpage
[youtube] xqUyaoFcJck: Downloading android player API JSON

WARNING: [youtube] xqUyaoFcJck: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = T6jMXAhHZ8Qqw9_WAEn ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] xqUyaoFcJck: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Cosinus & Daksinamurti - All Things Must Pass (360 Video) xqUyaoFcJck.webm
[download] 100% of    8.81MiB in 00:00:00 at 11.46MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Cosinus & Daksinamurti - All Things Must Pass (360 Video) xqUyaoFcJck.mp3
Deleting original file D:\sound\youtube\Cosinus & Daksinamurti - All Things Must Pass (360 Video) xqUyaoFcJck.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=C-i0eLKwSUo
[youtube] C-i0eLKwSUo: Downloading webpage
[youtube] C-i0eLKwSUo: Downloading android player API JSON
[info] C-i0eLKwSUo: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Cyk - Metalanguage C-i0eLKwSUo.webm
[download] 100% of    7.55MiB in 00:00:01 at 6.07MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Cyk - Metalanguage C-i0eLKwSUo.mp3
Deleting original file D:\sound\youtube\Cyk - Metalanguage C-i0eLKwSUo.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=C-i0eLKwSUo
[youtube] C-i0eLKwSUo: Downloading webpage
[youtube] C-i0eLKwSUo: Downloading android player API JSON
[info] C-i0eLKwSUo: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Cyk - Metalanguage C-i0eLKwSUo.webm
[download] 100% of    7.55MiB in 00:00:00 at 13.01MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Cyk - Metalanguage C-i0eLKwSUo.mp3
Deleting original file D:\sound\youtube\Cyk - Metalanguage C-i0eLKwSUo.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=K07yS_6sD-o
[youtube] K07yS_6sD-o: Downloading webpage
[youtube] K07yS_6sD-o: Downloading android player API JSON
[info] K07yS_6sD-o: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Cyk - Dotcom Honeymoon K07yS_6sD-o.webm
[download] 100% of    7.24MiB in 00:00:01 at 5.83MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Cyk - Dotcom Honeymoon K07yS_6sD-o.mp3
Deleting original file D:\sound\youtube\Cyk - Dotcom Honeymoon K07yS_6sD-o.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=1J-Qb6WO3XA
[youtube] 1J-Qb6WO3XA: Downloading webpage
[youtube] 1J-Qb6WO3XA: Downloading android player API JSON
[info] 1J-Qb6WO3XA: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Cyk - Ancestor Cyk 1J-Qb6WO3XA.webm
[download] 100% of    7.03MiB in 00:00:00 at 10.35MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Cyk - Ancestor Cyk 1J-Qb6WO3XA.mp3
Deleting original file D:\sound\youtube\Cyk - Ancestor Cyk 1J-Qb6WO3XA.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=HnGu6GccwR0
[youtube] HnGu6GccwR0: Downloading webpage
[youtube] HnGu6GccwR0: Downloading android player API JSON

WARNING: [youtube] HnGu6GccwR0: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = juuZysAnG9D07Tp6lEq ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] HnGu6GccwR0: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Cyk & Konebu - Paronomasia HnGu6GccwR0.webm
[download] 100% of    6.78MiB in 00:00:00 at 7.12MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Cyk & Konebu - Paronomasia HnGu6GccwR0.mp3
Deleting original file D:\sound\youtube\Cyk & Konebu - Paronomasia HnGu6GccwR0.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=qXBU1Cl0600
[youtube] qXBU1Cl0600: Downloading webpage
[youtube] qXBU1Cl0600: Downloading android player API JSON
[info] qXBU1Cl0600: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Ingrained Instincts - Cyclical Flow qXBU1Cl0600.webm
[download] 100% of    8.04MiB in 00:00:01 at 6.79MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Ingrained Instincts - Cyclical Flow qXBU1Cl0600.mp3
Deleting original file D:\sound\youtube\Ingrained Instincts - Cyclical Flow qXBU1Cl0600.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=qXBU1Cl0600
[youtube] qXBU1Cl0600: Downloading webpage
[youtube] qXBU1Cl0600: Downloading android player API JSON
[info] qXBU1Cl0600: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Ingrained Instincts - Cyclical Flow qXBU1Cl0600.webm
[download] 100% of    8.04MiB in 00:00:00 at 13.98MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Ingrained Instincts - Cyclical Flow qXBU1Cl0600.mp3
Deleting original file D:\sound\youtube\Ingrained Instincts - Cyclical Flow qXBU1Cl0600.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=iirV14r7mig
[youtube] iirV14r7mig: Downloading webpage
[youtube] iirV14r7mig: Downloading android player API JSON
[info] iirV14r7mig: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Ingrained Instincts - A Dancefloor Odyssey iirV14r7mig.webm
[download] 100% of    7.64MiB in 00:00:00 at 8.28MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Ingrained Instincts - A Dancefloor Odyssey iirV14r7mig.mp3
Deleting original file D:\sound\youtube\Ingrained Instincts - A Dancefloor Odyssey iirV14r7mig.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=FGSuWC83e4A
[youtube] FGSuWC83e4A: Downloading webpage
[youtube] FGSuWC83e4A: Downloading android player API JSON
[info] FGSuWC83e4A: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Ingrained Instincts - Shooting Colors FGSuWC83e4A.webm
[download] 100% of    7.46MiB in 00:00:01 at 3.88MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Ingrained Instincts - Shooting Colors FGSuWC83e4A.mp3
Deleting original file D:\sound\youtube\Ingrained Instincts - Shooting Colors FGSuWC83e4A.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=NLjI7QR1xl4
[youtube] NLjI7QR1xl4: Downloading webpage
[youtube] NLjI7QR1xl4: Downloading android player API JSON
[info] NLjI7QR1xl4: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Ingrained Instincts - We are Here to Fly (with Daksinamurti) NLjI7QR1xl4.webm
[download] 100% of    7.35MiB in 00:00:00 at 9.45MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Ingrained Instincts - We are Here to Fly (with Daksinamurti) NLjI7QR1xl4.mp3
Deleting original file D:\sound\youtube\Ingrained Instincts - We are Here to Fly (with Daksinamurti) NLjI7QR1xl4.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Mtw5UwvRMcY
[youtube] Mtw5UwvRMcY: Downloading webpage
[youtube] Mtw5UwvRMcY: Downloading android player API JSON

WARNING: [youtube] Mtw5UwvRMcY: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = D8gP6J5iYw1FI2PJgcH ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] Mtw5UwvRMcY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Ingrained Instincts - Spacefaring Species Mtw5UwvRMcY.webm
[download] 100% of    7.43MiB in 00:00:01 at 7.17MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Ingrained Instincts - Spacefaring Species Mtw5UwvRMcY.mp3
Deleting original file D:\sound\youtube\Ingrained Instincts - Spacefaring Species Mtw5UwvRMcY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Z8icl7DXoYc
[youtube] Z8icl7DXoYc: Downloading webpage
[youtube] Z8icl7DXoYc: Downloading android player API JSON
[info] Z8icl7DXoYc: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Ingrained Instincts - 11 Dimensions (with Nektarios) Z8icl7DXoYc.webm
[download] 100% of    7.53MiB in 00:00:01 at 4.46MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Ingrained Instincts - 11 Dimensions (with Nektarios) Z8icl7DXoYc.mp3
Deleting original file D:\sound\youtube\Ingrained Instincts - 11 Dimensions (with Nektarios) Z8icl7DXoYc.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=fIu6bE-elJU
[youtube] fIu6bE-elJU: Downloading webpage
[youtube] fIu6bE-elJU: Downloading android player API JSON
[info] fIu6bE-elJU: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Ingrained Instincts - Invent the Future fIu6bE-elJU.webm
[download] 100% of    7.45MiB in 00:00:00 at 11.07MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Ingrained Instincts - Invent the Future fIu6bE-elJU.mp3
Deleting original file D:\sound\youtube\Ingrained Instincts - Invent the Future fIu6bE-elJU.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=UCbf0qs_2Bs
[youtube] UCbf0qs_2Bs: Downloading webpage
[youtube] UCbf0qs_2Bs: Downloading android player API JSON
[info] UCbf0qs_2Bs: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Ingrained Instincts - Exponential Mindset (with Jumpstreet) UCbf0qs_2Bs.webm
[download] 100% of    8.41MiB in 00:00:00 at 9.17MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Ingrained Instincts - Exponential Mindset (with Jumpstreet) UCbf0qs_2Bs.mp3
Deleting original file D:\sound\youtube\Ingrained Instincts - Exponential Mindset (with Jumpstreet) UCbf0qs_2Bs.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=eXh7AnigqB4
[youtube] eXh7AnigqB4: Downloading webpage
[youtube] eXh7AnigqB4: Downloading android player API JSON
[info] eXh7AnigqB4: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Ingrained Instincts - Omega Point eXh7AnigqB4.webm
[download] 100% of    7.34MiB in 00:00:00 at 7.95MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Ingrained Instincts - Omega Point eXh7AnigqB4.mp3
Deleting original file D:\sound\youtube\Ingrained Instincts - Omega Point eXh7AnigqB4.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=zQg2GV69IvI
[youtube] zQg2GV69IvI: Downloading webpage
[youtube] zQg2GV69IvI: Downloading android player API JSON
[info] zQg2GV69IvI: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Fungus Funk & Assioma - Fractal Funk zQg2GV69IvI.webm
[download] 100% of    7.45MiB in 00:00:00 at 10.15MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Fungus Funk & Assioma - Fractal Funk zQg2GV69IvI.mp3
Deleting original file D:\sound\youtube\Fungus Funk & Assioma - Fractal Funk zQg2GV69IvI.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=zQg2GV69IvI
[youtube] zQg2GV69IvI: Downloading webpage
[youtube] zQg2GV69IvI: Downloading android player API JSON
[info] zQg2GV69IvI: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Fungus Funk & Assioma - Fractal Funk zQg2GV69IvI.webm
[download] 100% of    7.45MiB in 00:00:00 at 13.84MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Fungus Funk & Assioma - Fractal Funk zQg2GV69IvI.mp3
Deleting original file D:\sound\youtube\Fungus Funk & Assioma - Fractal Funk zQg2GV69IvI.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Ndpgsx57dgI
[youtube] Ndpgsx57dgI: Downloading webpage
[youtube] Ndpgsx57dgI: Downloading android player API JSON
[info] Ndpgsx57dgI: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Fungus Funk & Liftshift - Kush Tea Ndpgsx57dgI.webm
[download] 100% of    7.42MiB in 00:00:00 at 10.16MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Fungus Funk & Liftshift - Kush Tea Ndpgsx57dgI.mp3
Deleting original file D:\sound\youtube\Fungus Funk & Liftshift - Kush Tea Ndpgsx57dgI.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=MdzNlXnQQok
[youtube] MdzNlXnQQok: Downloading webpage
[youtube] MdzNlXnQQok: Downloading android player API JSON
[info] MdzNlXnQQok: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yab Yum - Orgones (Fungus Funk Remix) MdzNlXnQQok.webm
[download] 100% of    8.32MiB in 00:00:00 at 9.24MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yab Yum - Orgones (Fungus Funk Remix) MdzNlXnQQok.mp3
Deleting original file D:\sound\youtube\Yab Yum - Orgones (Fungus Funk Remix) MdzNlXnQQok.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=RCwdNzZNidk
[youtube] RCwdNzZNidk: Downloading webpage
[youtube] RCwdNzZNidk: Downloading android player API JSON

WARNING: [youtube] RCwdNzZNidk: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = jl9hUzJnkZe-zITQK4R ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] RCwdNzZNidk: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's & Earthworm - Storm Breaker RCwdNzZNidk.webm
[download] 100% of    6.72MiB in 00:00:00 at 7.76MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's & Earthworm - Storm Breaker RCwdNzZNidk.mp3
Deleting original file D:\sound\youtube\Doom's & Earthworm - Storm Breaker RCwdNzZNidk.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=RCwdNzZNidk
[youtube] RCwdNzZNidk: Downloading webpage
[youtube] RCwdNzZNidk: Downloading android player API JSON

WARNING: [youtube] RCwdNzZNidk: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = Tiq4sSZrATnDBS9C07N ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] RCwdNzZNidk: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's & Earthworm - Storm Breaker RCwdNzZNidk.webm
[download] 100% of    6.72MiB in 00:00:00 at 12.69MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's & Earthworm - Storm Breaker RCwdNzZNidk.mp3
Deleting original file D:\sound\youtube\Doom's & Earthworm - Storm Breaker RCwdNzZNidk.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=FedDotctQI4
[youtube] FedDotctQI4: Downloading webpage
[youtube] FedDotctQI4: Downloading android player API JSON
[info] FedDotctQI4: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's - Splitting Of Thought FedDotctQI4.webm
[download] 100% of    6.40MiB in 00:00:00 at 7.51MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's - Splitting Of Thought FedDotctQI4.mp3
Deleting original file D:\sound\youtube\Doom's - Splitting Of Thought FedDotctQI4.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=o1aykNryA8M
[youtube] o1aykNryA8M: Downloading webpage
[youtube] o1aykNryA8M: Downloading android player API JSON
[info] o1aykNryA8M: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's - Back To The Future o1aykNryA8M.webm
[download] 100% of    6.43MiB in 00:00:01 at 4.42MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's - Back To The Future o1aykNryA8M.mp3
Deleting original file D:\sound\youtube\Doom's - Back To The Future o1aykNryA8M.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=xQK4SOnowBk
[youtube] xQK4SOnowBk: Downloading webpage
[youtube] xQK4SOnowBk: Downloading android player API JSON
[info] xQK4SOnowBk: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's - Brain Driver xQK4SOnowBk.webm
[download] 100% of    6.79MiB in 00:00:00 at 7.48MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's - Brain Driver xQK4SOnowBk.mp3
Deleting original file D:\sound\youtube\Doom's - Brain Driver xQK4SOnowBk.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=1F37_3UqfGU
[youtube] 1F37_3UqfGU: Downloading webpage
[youtube] 1F37_3UqfGU: Downloading android player API JSON
[info] 1F37_3UqfGU: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's & Wood Warden - Retro Futura 1F37_3UqfGU.webm
[download] 100% of    7.97MiB in 00:00:00 at 10.37MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's & Wood Warden - Retro Futura 1F37_3UqfGU.mp3
Deleting original file D:\sound\youtube\Doom's & Wood Warden - Retro Futura 1F37_3UqfGU.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=dLoU60JztN4
[youtube] dLoU60JztN4: Downloading webpage
[youtube] dLoU60JztN4: Downloading android player API JSON
[info] dLoU60JztN4: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's & Yabba Dabba - LFO For Pillow dLoU60JztN4.webm
[download] 100% of    6.48MiB in 00:00:00 at 8.33MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's & Yabba Dabba - LFO For Pillow dLoU60JztN4.mp3
Deleting original file D:\sound\youtube\Doom's & Yabba Dabba - LFO For Pillow dLoU60JztN4.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=8gm8bq8VxsY
[youtube] 8gm8bq8VxsY: Downloading webpage
[youtube] 8gm8bq8VxsY: Downloading android player API JSON

WARNING: [youtube] 8gm8bq8VxsY: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = TZjqZBR1kuCVsN9BNLZ ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] 8gm8bq8VxsY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's - Transpose The Time 8gm8bq8VxsY.webm
[download] 100% of    6.67MiB in 00:00:00 at 8.15MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's - Transpose The Time 8gm8bq8VxsY.mp3
Deleting original file D:\sound\youtube\Doom's - Transpose The Time 8gm8bq8VxsY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=4JTXZGrJ9pM
[youtube] 4JTXZGrJ9pM: Downloading webpage
[youtube] 4JTXZGrJ9pM: Downloading android player API JSON
[info] 4JTXZGrJ9pM: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's - Jungle Groove 4JTXZGrJ9pM.webm
[download] 100% of    6.00MiB in 00:00:01 at 4.72MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's - Jungle Groove 4JTXZGrJ9pM.mp3
Deleting original file D:\sound\youtube\Doom's - Jungle Groove 4JTXZGrJ9pM.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=ZzRDaj1XW6s
[youtube] ZzRDaj1XW6s: Downloading webpage
[youtube] ZzRDaj1XW6s: Downloading android player API JSON

WARNING: [youtube] ZzRDaj1XW6s: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = DJUpOpG_vTtx71nNmW4 ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] ZzRDaj1XW6s: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's - Mystical World ZzRDaj1XW6s.webm
[download] 100% of    7.41MiB in 00:00:01 at 4.11MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's - Mystical World ZzRDaj1XW6s.mp3
Deleting original file D:\sound\youtube\Doom's - Mystical World ZzRDaj1XW6s.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=l9uTeKTEgRc
[youtube] l9uTeKTEgRc: Downloading webpage
[youtube] l9uTeKTEgRc: Downloading android player API JSON
[info] l9uTeKTEgRc: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Doom's - Gary Is Not Just A Snail l9uTeKTEgRc.webm
[download] 100% of    6.04MiB in 00:00:03 at 1.68MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Doom's - Gary Is Not Just A Snail l9uTeKTEgRc.mp3
Deleting original file D:\sound\youtube\Doom's - Gary Is Not Just A Snail l9uTeKTEgRc.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=l6ghdOKStZ0
[youtube] l6ghdOKStZ0: Downloading webpage
[youtube] l6ghdOKStZ0: Downloading android player API JSON
[info] l6ghdOKStZ0: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Uka Uka & Diksha - Synthesizer l6ghdOKStZ0.webm
[download] 100% of    7.86MiB in 00:00:00 at 8.66MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Uka Uka & Diksha - Synthesizer l6ghdOKStZ0.mp3
Deleting original file D:\sound\youtube\Uka Uka & Diksha - Synthesizer l6ghdOKStZ0.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=l6ghdOKStZ0
[youtube] l6ghdOKStZ0: Downloading webpage
[youtube] l6ghdOKStZ0: Downloading android player API JSON
[info] l6ghdOKStZ0: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Uka Uka & Diksha - Synthesizer l6ghdOKStZ0.webm
[download] 100% of    7.86MiB in 00:00:00 at 14.30MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Uka Uka & Diksha - Synthesizer l6ghdOKStZ0.mp3
Deleting original file D:\sound\youtube\Uka Uka & Diksha - Synthesizer l6ghdOKStZ0.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=wFOyhBMql6c
[youtube] wFOyhBMql6c: Downloading webpage
[youtube] wFOyhBMql6c: Downloading android player API JSON
[info] wFOyhBMql6c: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Uka Uka & Slide - Akuma wFOyhBMql6c.webm
[download] 100% of    7.45MiB in 00:00:00 at 11.91MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Uka Uka & Slide - Akuma wFOyhBMql6c.mp3
Deleting original file D:\sound\youtube\Uka Uka & Slide - Akuma wFOyhBMql6c.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=JzQJY2G2XJs
[youtube] JzQJY2G2XJs: Downloading webpage
[youtube] JzQJY2G2XJs: Downloading android player API JSON

WARNING: [youtube] JzQJY2G2XJs: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = jISNzBn5H-QVvzZKVp2 ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] JzQJY2G2XJs: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Uka Uka & Futuro - Quantum Simulator JzQJY2G2XJs.webm
[download] 100% of    8.54MiB in 00:00:00 at 10.59MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Uka Uka & Futuro - Quantum Simulator JzQJY2G2XJs.mp3
Deleting original file D:\sound\youtube\Uka Uka & Futuro - Quantum Simulator JzQJY2G2XJs.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=uAnQyQtZOVg
[youtube] uAnQyQtZOVg: Downloading webpage
[youtube] uAnQyQtZOVg: Downloading android player API JSON
[info] uAnQyQtZOVg: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Uka Uka & Hypereggs - Microland uAnQyQtZOVg.webm
[download] 100% of    7.51MiB in 00:00:00 at 10.40MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Uka Uka & Hypereggs - Microland uAnQyQtZOVg.mp3
Deleting original file D:\sound\youtube\Uka Uka & Hypereggs - Microland uAnQyQtZOVg.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=vwkW7vnAyeo
[youtube] vwkW7vnAyeo: Downloading webpage
[youtube] vwkW7vnAyeo: Downloading android player API JSON
[info] vwkW7vnAyeo: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Hierophants - Velum vwkW7vnAyeo.webm
[download] 100% of    7.96MiB in 00:00:01 at 7.81MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Hierophants - Velum vwkW7vnAyeo.mp3
Deleting original file D:\sound\youtube\Hierophants - Velum vwkW7vnAyeo.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=vwkW7vnAyeo
[youtube] vwkW7vnAyeo: Downloading webpage
[youtube] vwkW7vnAyeo: Downloading android player API JSON
[info] vwkW7vnAyeo: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Hierophants - Velum vwkW7vnAyeo.webm
[download] 100% of    7.96MiB in 00:00:00 at 13.88MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Hierophants - Velum vwkW7vnAyeo.mp3
Deleting original file D:\sound\youtube\Hierophants - Velum vwkW7vnAyeo.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=GxPyIQcK7LQ
[youtube] GxPyIQcK7LQ: Downloading webpage
[youtube] GxPyIQcK7LQ: Downloading android player API JSON
[info] GxPyIQcK7LQ: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Hierophants - Bending Pipes GxPyIQcK7LQ.webm
[download] 100% of    9.08MiB in 00:00:00 at 9.93MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Hierophants - Bending Pipes GxPyIQcK7LQ.mp3
Deleting original file D:\sound\youtube\Hierophants - Bending Pipes GxPyIQcK7LQ.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=UkrlWUl6RB4
[youtube] UkrlWUl6RB4: Downloading webpage
[youtube] UkrlWUl6RB4: Downloading android player API JSON
[info] UkrlWUl6RB4: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Hierophants - Hieroglyphs UkrlWUl6RB4.webm
[download] 100% of    7.91MiB in 00:00:00 at 10.27MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Hierophants - Hieroglyphs UkrlWUl6RB4.mp3
Deleting original file D:\sound\youtube\Hierophants - Hieroglyphs UkrlWUl6RB4.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=GOrSLcTrObM
[youtube] GOrSLcTrObM: Downloading webpage
[youtube] GOrSLcTrObM: Downloading android player API JSON
[info] GOrSLcTrObM: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Hierophants - Entremundos GOrSLcTrObM.webm
[download] 100% of    7.73MiB in 00:00:00 at 8.80MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Hierophants - Entremundos GOrSLcTrObM.mp3
Deleting original file D:\sound\youtube\Hierophants - Entremundos GOrSLcTrObM.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=NFnbW_Z7g64
[youtube] NFnbW_Z7g64: Downloading webpage
[youtube] NFnbW_Z7g64: Downloading android player API JSON

WARNING: [youtube] NFnbW_Z7g64: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = DDJp9kFZFzEda6DMsnk ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] NFnbW_Z7g64: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Vertical - Moonbow NFnbW_Z7g64.webm
[download] 100% of    6.57MiB in 00:00:00 at 7.55MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Vertical - Moonbow NFnbW_Z7g64.mp3
Deleting original file D:\sound\youtube\Vertical - Moonbow NFnbW_Z7g64.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=NFnbW_Z7g64
[youtube] NFnbW_Z7g64: Downloading webpage
[youtube] NFnbW_Z7g64: Downloading android player API JSON

WARNING: [youtube] NFnbW_Z7g64: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = zyp3xJczUX6Ubum6YcO ; player = https://www.youtube.com/s/player/f565d246/player_ias.vflset/en_US/base.js

[info] NFnbW_Z7g64: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Vertical - Moonbow NFnbW_Z7g64.webm
[download] 100% of    6.57MiB in 00:00:00 at 8.76MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Vertical - Moonbow NFnbW_Z7g64.mp3
Deleting original file D:\sound\youtube\Vertical - Moonbow NFnbW_Z7g64.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=tuCZl6IdjAU
[youtube] tuCZl6IdjAU: Downloading webpage
[youtube] tuCZl6IdjAU: Downloading android player API JSON
[info] tuCZl6IdjAU: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Yebah - The Number tuCZl6IdjAU.webm
[download] 100% of    8.41MiB in 00:00:01 at 5.16MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Yebah - The Number tuCZl6IdjAU.mp3
Deleting original file D:\sound\youtube\Yebah - The Number tuCZl6IdjAU.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=mv5eaBssA6c
[youtube] mv5eaBssA6c: Downloading webpage
[youtube] mv5eaBssA6c: Downloading android player API JSON
[info] mv5eaBssA6c: Downloading 1 format(s): 251

[download] Got error: <urlopen error timed out>

[youtube] Extracting URL: http://www.youtube.com/watch?v=Iv71xzefhxY
[youtube] Iv71xzefhxY: Downloading webpage
[youtube] Iv71xzefhxY: Downloading android player API JSON
[info] Iv71xzefhxY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm
[download] 100% of   79.07MiB in 00:00:08 at 9.00MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.mp3
Deleting original file D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Iv71xzefhxY
[youtube] Iv71xzefhxY: Downloading webpage
[youtube] Iv71xzefhxY: Downloading android player API JSON
[info] Iv71xzefhxY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm
[download] 100% of   79.07MiB in 00:00:09 at 8.28MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.mp3
Deleting original file D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=TFXJvOpQaXA
[youtube] TFXJvOpQaXA: Downloading webpage
[youtube] TFXJvOpQaXA: Downloading android player API JSON
[info] TFXJvOpQaXA: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.webm
[download] 100% of    1.68MiB in 00:00:00 at 3.32MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.mp3
Deleting original file D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=lGo2bGWHgUk
[youtube] lGo2bGWHgUk: Downloading webpage
[youtube] lGo2bGWHgUk: Downloading android player API JSON
[info] lGo2bGWHgUk: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.webm
[download] 100% of   60.72MiB in 00:00:07 at 8.51MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.mp3
Deleting original file D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=GUsH5iX1cw0
[youtube] GUsH5iX1cw0: Downloading webpage
[youtube] GUsH5iX1cw0: Downloading android player API JSON
[info] GUsH5iX1cw0: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society [Ep.3]： Cosinus [Trailer] GUsH5iX1cw0.webm
[download] 100% of    1.23MiB in 00:00:00 at 2.98MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society [Ep.3]： Cosinus [Trailer] GUsH5iX1cw0.mp3
Deleting original file D:\sound\youtube\The Sangoma Society [Ep.3]： Cosinus [Trailer] GUsH5iX1cw0.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=SItOLqk7w0E
[youtube] SItOLqk7w0E: Downloading webpage
[youtube] SItOLqk7w0E: Downloading android player API JSON
[info] SItOLqk7w0E: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society [Ep.4]： DJ sG4rY [Trailer] SItOLqk7w0E.webm
[download] 100% of    2.72MiB in 00:00:00 at 7.53MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society [Ep.4]： DJ sG4rY [Trailer] SItOLqk7w0E.mp3
Deleting original file D:\sound\youtube\The Sangoma Society [Ep.4]： DJ sG4rY [Trailer] SItOLqk7w0E.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=F2s820Btvns
[youtube] F2s820Btvns: Downloading webpage
[youtube] F2s820Btvns: Downloading android player API JSON
[info] F2s820Btvns: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Jumpstreet & Mavzy - Pardon？ D’accord! F2s820Btvns.webm
[download] 100% of    6.84MiB in 00:00:00 at 10.16MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Jumpstreet & Mavzy - Pardon？ D’accord! F2s820Btvns.mp3
Deleting original file D:\sound\youtube\Jumpstreet & Mavzy - Pardon？ D’accord! F2s820Btvns.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=mv5eaBssA6c
[youtube] mv5eaBssA6c: Downloading webpage
[youtube] mv5eaBssA6c: Downloading android player API JSON
[info] mv5eaBssA6c: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Kabayun - Escape Velocity (Feat. Delytic) mv5eaBssA6c.webm
[download] 100% of    8.12MiB in 00:00:00 at 10.75MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Kabayun - Escape Velocity (Feat. Delytic) mv5eaBssA6c.mp3
Deleting original file D:\sound\youtube\Kabayun - Escape Velocity (Feat. Delytic) mv5eaBssA6c.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=piuVhRJ7BwE
[youtube] piuVhRJ7BwE: Downloading webpage
[youtube] piuVhRJ7BwE: Downloading android player API JSON
[info] piuVhRJ7BwE: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Sequoya & Cosinus - Dark Energies piuVhRJ7BwE.webm
[download] 100% of    7.81MiB in 00:00:00 at 8.37MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Sequoya & Cosinus - Dark Energies piuVhRJ7BwE.mp3
Deleting original file D:\sound\youtube\Sequoya & Cosinus - Dark Energies piuVhRJ7BwE.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=qsd8DZtmZrM
[youtube] qsd8DZtmZrM: Downloading webpage
[youtube] qsd8DZtmZrM: Downloading android player API JSON
[info] qsd8DZtmZrM: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Gu - Sonic Weapon qsd8DZtmZrM.webm
[download] 100% of    7.10MiB in 00:00:02 at 2.70MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Gu - Sonic Weapon qsd8DZtmZrM.mp3
Deleting original file D:\sound\youtube\Gu - Sonic Weapon qsd8DZtmZrM.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=960fMzFBh7Q
[youtube] 960fMzFBh7Q: Downloading webpage
[youtube] 960fMzFBh7Q: Downloading android player API JSON
[info] 960fMzFBh7Q: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Kaos - A Real Good Time 960fMzFBh7Q.webm
[download] 100% of    7.28MiB in 00:00:01 at 7.05MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Kaos - A Real Good Time 960fMzFBh7Q.mp3
Deleting original file D:\sound\youtube\Kaos - A Real Good Time 960fMzFBh7Q.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=fFYB06N_nlQ
[youtube] fFYB06N_nlQ: Downloading webpage
[youtube] fFYB06N_nlQ: Downloading android player API JSON
[info] fFYB06N_nlQ: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Nargun & The Verge - Birds of Paradise fFYB06N_nlQ.webm
[download] 100% of    8.11MiB in 00:00:03 at 2.60MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Nargun & The Verge - Birds of Paradise fFYB06N_nlQ.mp3
Deleting original file D:\sound\youtube\Nargun & The Verge - Birds of Paradise fFYB06N_nlQ.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=MqA6zaHM7PE
[youtube] MqA6zaHM7PE: Downloading webpage
[youtube] MqA6zaHM7PE: Downloading android player API JSON
[info] MqA6zaHM7PE: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Archaic - Animystic MqA6zaHM7PE.webm
[download] 100% of    8.85MiB in 00:00:02 at 4.06MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Archaic - Animystic MqA6zaHM7PE.mp3
Deleting original file D:\sound\youtube\Archaic - Animystic MqA6zaHM7PE.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=hTVH_R6X2-8
[youtube] hTVH_R6X2-8: Downloading webpage
[youtube] hTVH_R6X2-8: Downloading android player API JSON
[info] hTVH_R6X2-8: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Tengri - Yantra On The Nightsky hTVH_R6X2-8.webm
[download] 100% of    6.71MiB in 00:00:01 at 3.45MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Tengri - Yantra On The Nightsky hTVH_R6X2-8.mp3
Deleting original file D:\sound\youtube\Tengri - Yantra On The Nightsky hTVH_R6X2-8.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=oJJ4toI_yn0
[youtube] oJJ4toI_yn0: Downloading webpage
[youtube] oJJ4toI_yn0: Downloading android player API JSON
[info] oJJ4toI_yn0: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Egon's Embrace - Sleight of Hand oJJ4toI_yn0.webm
[download] 100% of    9.40MiB in 00:00:01 at 8.81MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Egon's Embrace - Sleight of Hand oJJ4toI_yn0.mp3
Deleting original file D:\sound\youtube\Egon's Embrace - Sleight of Hand oJJ4toI_yn0.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Iv71xzefhxY
[youtube] Iv71xzefhxY: Downloading webpage
[youtube] Iv71xzefhxY: Downloading android player API JSON
[info] Iv71xzefhxY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm
[download] 100% of   79.07MiB in 00:00:08 at 9.16MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.mp3
Deleting original file D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Iv71xzefhxY
[youtube] Iv71xzefhxY: Downloading webpage
[youtube] Iv71xzefhxY: Downloading android player API JSON
[info] Iv71xzefhxY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm
[download] 100% of   79.07MiB in 00:00:08 at 9.19MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.mp3
Deleting original file D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=TFXJvOpQaXA
[youtube] TFXJvOpQaXA: Downloading webpage
[youtube] TFXJvOpQaXA: Downloading android player API JSON
[info] TFXJvOpQaXA: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.webm
[download] 100% of    1.68MiB in 00:00:00 at 4.01MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.mp3
Deleting original file D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=lGo2bGWHgUk
[youtube] lGo2bGWHgUk: Downloading webpage
[youtube] lGo2bGWHgUk: Downloading android player API JSON
[info] lGo2bGWHgUk: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.webm
[download] 100% of   60.72MiB in 00:00:06 at 9.87MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.mp3
Deleting original file D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=GUsH5iX1cw0
[youtube] GUsH5iX1cw0: Downloading webpage
[youtube] GUsH5iX1cw0: Downloading android player API JSON
[info] GUsH5iX1cw0: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society [Ep.3]： Cosinus [Trailer] GUsH5iX1cw0.webm
[download] 100% of    1.23MiB in 00:00:00 at 3.87MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society [Ep.3]： Cosinus [Trailer] GUsH5iX1cw0.mp3
Deleting original file D:\sound\youtube\The Sangoma Society [Ep.3]： Cosinus [Trailer] GUsH5iX1cw0.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=SItOLqk7w0E
[youtube] SItOLqk7w0E: Downloading webpage
[youtube] SItOLqk7w0E: Downloading android player API JSON
[info] SItOLqk7w0E: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society [Ep.4]： DJ sG4rY [Trailer] SItOLqk7w0E.webm
[download] 100% of    2.72MiB in 00:00:00 at 7.26MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society [Ep.4]： DJ sG4rY [Trailer] SItOLqk7w0E.mp3
Deleting original file D:\sound\youtube\The Sangoma Society [Ep.4]： DJ sG4rY [Trailer] SItOLqk7w0E.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=F2s820Btvns
[youtube] F2s820Btvns: Downloading webpage
[youtube] F2s820Btvns: Downloading android player API JSON
[info] F2s820Btvns: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Jumpstreet & Mavzy - Pardon？ D’accord! F2s820Btvns.webm
[download] 100% of    6.84MiB in 00:00:00 at 12.38MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Jumpstreet & Mavzy - Pardon？ D’accord! F2s820Btvns.mp3
Deleting original file D:\sound\youtube\Jumpstreet & Mavzy - Pardon？ D’accord! F2s820Btvns.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Iv71xzefhxY
[youtube] Iv71xzefhxY: Downloading webpage
[youtube] Iv71xzefhxY: Downloading android player API JSON
[info] Iv71xzefhxY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm
[download] 100% of   79.07MiB in 00:00:08 at 8.95MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.mp3
Deleting original file D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Iv71xzefhxY
[youtube] Iv71xzefhxY: Downloading webpage
[youtube] Iv71xzefhxY: Downloading android player API JSON
[info] Iv71xzefhxY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm
[download] 100% of   79.07MiB in 00:00:08 at 9.00MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.mp3
Deleting original file D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=TFXJvOpQaXA
[youtube] TFXJvOpQaXA: Downloading webpage
[youtube] TFXJvOpQaXA: Downloading android player API JSON
[info] TFXJvOpQaXA: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.webm
[download] 100% of    1.68MiB in 00:00:00 at 4.49MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.mp3
Deleting original file D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=lGo2bGWHgUk
[youtube] lGo2bGWHgUk: Downloading webpage
[youtube] lGo2bGWHgUk: Downloading android player API JSON
[info] lGo2bGWHgUk: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.webm
[download] 100% of   60.72MiB in 00:00:05 at 10.13MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.mp3
Deleting original file D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=GUsH5iX1cw0
[youtube] GUsH5iX1cw0: Downloading webpage
[youtube] GUsH5iX1cw0: Downloading android player API JSON
[info] GUsH5iX1cw0: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society [Ep.3]： Cosinus [Trailer] GUsH5iX1cw0.webm
[download] 100% of    1.23MiB in 00:00:00 at 3.53MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society [Ep.3]： Cosinus [Trailer] GUsH5iX1cw0.mp3
Deleting original file D:\sound\youtube\The Sangoma Society [Ep.3]： Cosinus [Trailer] GUsH5iX1cw0.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=SItOLqk7w0E
[youtube] SItOLqk7w0E: Downloading webpage
[youtube] SItOLqk7w0E: Downloading android player API JSON
[info] SItOLqk7w0E: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society [Ep.4]： DJ sG4rY [Trailer] SItOLqk7w0E.webm
[download] 100% of    2.72MiB in 00:00:00 at 6.10MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society [Ep.4]： DJ sG4rY [Trailer] SItOLqk7w0E.mp3
Deleting original file D:\sound\youtube\The Sangoma Society [Ep.4]： DJ sG4rY [Trailer] SItOLqk7w0E.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=F2s820Btvns
[youtube] F2s820Btvns: Downloading webpage
[youtube] F2s820Btvns: Downloading android player API JSON
[info] F2s820Btvns: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\Jumpstreet & Mavzy - Pardon？ D’accord! F2s820Btvns.webm
[download] 100% of    6.84MiB in 00:00:00 at 8.70MiB/s
[ExtractAudio] Destination: D:\sound\youtube\Jumpstreet & Mavzy - Pardon？ D’accord! F2s820Btvns.mp3
Deleting original file D:\sound\youtube\Jumpstreet & Mavzy - Pardon？ D’accord! F2s820Btvns.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Iv71xzefhxY
[youtube] Iv71xzefhxY: Downloading webpage
[youtube] Iv71xzefhxY: Downloading android player API JSON
[info] Iv71xzefhxY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm
[download] 100% of   79.07MiB in 00:00:08 at 8.81MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.mp3
Deleting original file D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=Iv71xzefhxY
[youtube] Iv71xzefhxY: Downloading webpage
[youtube] Iv71xzefhxY: Downloading android player API JSON
[info] Iv71xzefhxY: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm
[download] 100% of   79.07MiB in 00:00:09 at 8.04MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.mp3
Deleting original file D:\sound\youtube\The Sangoma Society podcast： Kabayun [Ep1] Iv71xzefhxY.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=TFXJvOpQaXA
[youtube] TFXJvOpQaXA: Downloading webpage
[youtube] TFXJvOpQaXA: Downloading android player API JSON
[info] TFXJvOpQaXA: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.webm
[download] 100% of    1.68MiB in 00:00:00 at 4.91MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.mp3
Deleting original file D:\sound\youtube\The Sangoma Society [Ep.2]： Raz Gaster [Trailer] TFXJvOpQaXA.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=lGo2bGWHgUk
[youtube] lGo2bGWHgUk: Downloading webpage
[youtube] lGo2bGWHgUk: Downloading android player API JSON
[info] lGo2bGWHgUk: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.webm
[download] 100% of   60.72MiB in 00:00:06 at 8.72MiB/s
[ExtractAudio] Destination: D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.mp3
Deleting original file D:\sound\youtube\The Sangoma Society Podcast： Raz Gaster [Ep2] lGo2bGWHgUk.webm (pass -k to keep)
[youtube] Extracting URL: http://www.youtube.com/watch?v=GUsH5iX1cw0
[youtube] GUsH5iX1cw0: Downloading webpage
[youtube] GUsH5iX1cw0: Downloading android player API JSON
[info] GUsH5iX1cw0: Downloading 1 format(s): 251
[download] Destination: D:\sound\youtube\The Sangoma Society [Ep.3]： Cosinus [Trailer] GUsH5iX1cw0.webm
[download] 100% of    1.23MiB in 00:00:00 at 3.24MiB/s

In [ ]:
from beets import importer
from beets.importer import library

library.

importer.ImportSession(,)